export const estimatingProjects = [
  {slug:'bookshelf',name:'Bookshelf',tag:'Furniture',intro:'Budget the repeated shelves before pricing the complete bookcase. Shelf depth and grain direction often decide whether an apparently spare strip is usable.',part:'Shelf',length:760,width:280,qty:5,stockLength:2440,stockWidth:1220,price:65,tool:'/examples/bookshelf-cut-list/',checks:['Measure the clear opening between the sides; overall cabinet width is not the shelf length.','Keep fixed shelves, adjustable shelves, sides and the back as separate part types.','Confirm shelf support, load and edge treatment before approving thickness.'],excluded:'Sides, back, plinth, edging, hardware and finishing are outside this shelf-only allowance.',next:'Enter the sides, shelves and back as reviewed parts in CutList. Keep different stock thicknesses in separate plans and check grain before generating the layout.'},
  {slug:'kitchen-cabinet',name:'Kitchen cabinet',tag:'Cabinet shop',intro:'Start with cabinet side panels, then build up the remaining stock groups. Carcass panels and thin backs cannot share one purchasing calculation simply because both are plywood.',part:'Carcass side',length:720,width:560,qty:4,stockLength:2440,stockWidth:1220,price:78,tool:'/cabinet-cut-list-calculator/',checks:['Measure the installation space and appliance clearances before deriving the carcass.','Deduct the construction-specific allowances for bottoms, rails and shelves.','List exposed edges and confirm hardware drilling and door gaps separately.'],excluded:'Bottoms, rails, backs, doors, worktop, hardware, fitting and backsplash are not included.',next:'Build the verified carcass parts in CutList, review the layout, then use the cutting sequence at the saw.',related:'tile'},
  {slug:'wardrobe',name:'Wardrobe',tag:'Fitted furniture',intro:'Check tall gables against available sheet length before estimating cost. A low area total is of little help if a full-height panel cannot fit the selected stock.',part:'Tall gable',length:2300,width:580,qty:3,stockLength:2440,stockWidth:1220,price:85,tool:'/tools/components/',checks:['Measure height at several points and allow for installation and levelling.','Keep visible grain running consistently across tall panels and doors.','Separate shelf, back and door stock, and check transport access for large parts.'],excluded:'Shelves, doors, tracks, hanging rails, backs and installation are additional.',next:'Use CutList to test the tall panels alongside the shorter parts. Save a checked revision before changing shelf spacing or door dimensions.'},
  {slug:'workbench',name:'Workbench',tag:'Workshop',intro:'Estimate a laminated sheet top one layer at a time. Two layers use twice the panel area, but the complete build also needs a separate base and fastening plan.',part:'Top layer',length:1800,width:750,qty:2,stockLength:2440,stockWidth:1220,price:60,tool:'/plywood-cut-calculator/',checks:['Confirm final top thickness and whether edges will be trimmed after bonding.','Check whether offcuts are actually large enough for useful shelves.','Plan the base, load support and fasteners independently of the top allowance.'],excluded:'Base lumber, lower shelf, adhesive, screws, vice and finish are excluded.',next:'Enter the top layers and any confirmed shelf parts in CutList. Inspect the cut order before breaking down the sheets.'},
  {slug:'under-stair-storage',name:'Under-stair storage',tag:'Interior fit-out',intro:'Estimate rectangular storage blanks beneath an existing stair. Sloped pieces require measured geometry: a rectangle allowance does not describe the final angled cut.',part:'Rectangular blank',length:1100,width:550,qty:4,stockLength:2440,stockWidth:1220,price:72,tool:'/plywood-cut-calculator/',checks:['Template the existing slope and check access, services and door swing.','Use bounding rectangles for this allowance; retain the angled offcut as waste until proven reusable.','Keep the storage design independent of the stair structure and required clearances.'],excluded:'Angled cut geometry, doors, hardware, services and structural stair work are excluded.',next:'Use CutList for the rectangular sheet blanks. Mark and verify the angled finishing cuts separately from the sheet layout.',related:'stairs'},
  {slug:'laundry-fit-out',name:'Laundry fit-out',tag:'Renovation',intro:'Budget cabinet panels separately from the tiled floor or splashback. Keeping the trades apart avoids mixing sheet yield with tile coverage and box rounding.',part:'Cabinet side',length:850,width:600,qty:4,stockLength:2440,stockWidth:1220,price:82,tool:'/cabinet-cut-list-calculator/',checks:['Confirm appliance dimensions, ventilation and service access from the actual equipment.','Specify panel suitability and exposed-edge treatment for the installation conditions.','Measure tile surfaces separately after identifying cabinet and appliance footprints.'],excluded:'Doors, backs, shelves, worktop, plumbing, electrical work and tile costs are additional.',next:'Finish the cabinet parts list in CutList. Plan the separate tiled surfaces in TileFit after checking the actual room measurements.',related:'tile'}
];
export const estimatingGuides = [
 ['units','Keep dimensions and prices in the same unit','Record dimensions in either millimeters or inches for the entire calculation. Switching units here converts the physical dimensions, including sheet size; it does not change the price per sheet. For solid lumber sold by volume, use the board-foot calculator instead of treating a board as sheet stock.','/board-foot-calculator/','Board-foot calculator'],
 ['billing','Separate finished sizes from billed stock','A supplier bills for the stock you buy, while the part dimensions describe what you need after processing. Check actual sheet size, usable edges, thickness and surface specification. Compare prices only after matching those details. A cheaper sheet with the wrong thickness or finish is not an equivalent quote.','/material-library/','Compare sheet materials'],
 ['allowance','Name the allowance before using a percentage','This estimator adds a purchasing allowance to net panel area: net area × (1 + allowance / 100). It is not a measured cutting-waste percentage or a guaranteed yield. A 10% allowance on 10 square meters gives 11 square meters; a 90% yield target would require 10 / 0.9 = 11.11 square meters.','/wood-waste-calculator/','Check waste calculations'],
 ['rounding','Round each stock group independently','Divide allowed area by sheet area and round up to whole sheets. Repeat separately for each material, thickness and finish. Do not combine a thin back with thick carcass panels to remove a sheet from the order. Keep any useful stock already on hand separate until its dimensions and condition have been checked.','/plywood-cut-calculator/','Check a sheet layout'],
 ['fit','Check part fit before trusting the total','Area is a lower-bound planning method, not a nesting algorithm. Parts can fail to pack because of their shape, grain, kerf or edge trim even when total area looks sufficient. This tool flags a single part that exceeds the stock dimensions, but only a reviewed layout can establish a practical sheet requirement.','/kerf-calculator/','Check saw kerf'],
 ['edges','Count exposed edges explicitly','Measure only the edges that will actually receive banding, then allow for end trimming and setup waste separately. Confirm whether your part dimensions describe the core panel or the finished banded part. Keep banding material and application labor outside the sheet price so neither is counted twice.','/tools/components/','Review component dimensions'],
 ['labor','Keep labor and purchased materials separate','Use estimated hours multiplied by your own hourly cost for this early allowance. Include setup and handling deliberately rather than hiding them in sheet waste. The output is a partial cost subtotal, not a client quote: hardware, transport, overhead, taxes and profit may still need their own lines.','/material-cost-calculator/','Review a wider material budget'],
 ['release','Review before ordering or cutting','Freeze the intended dimensions, stock specification, grain rules, kerf and trim before releasing a cut plan. In CutList, recreate and review those inputs, then generate the layout and follow the cutting sequence. Pro adds PDF export and AirPrint for the shop handoff. Opening the App Store from this page does not transfer your numbers.','/apps/cutlist/','See the CutList workflow']
];
