const issue = (slug, category, title, query, symptom, answer, causes, checks, fixSteps, prevention, stopCondition, links) => ({
  slug,
  category,
  title,
  query,
  symptom,
  answer,
  causes,
  checks,
  fixSteps,
  prevention,
  stopCondition,
  links,
});

export const troubleshootingIssues = [
  issue(
    "plywood-layout-does-not-fit",
    "Layouts",
    "Plywood Layout Does Not Fit: 7-Point Diagnosis",
    "a plywood cut layout that does not fit",
    "The parts appear to fit by total area, but the layout needs another sheet or leaves one part unplaced.",
    "Do not shrink a part to force the layout. First compare the largest part with the usable sheet, then verify trim, kerf, rotation, quantities, and material groups. Area proves only a lower bound; geometry decides whether the rectangles actually fit.",
    [
      ["Usable sheet is smaller than nominal", "Factory damage, edge trim, or supplier tolerance can reduce a 96 × 48 sheet before nesting starts."],
      ["One dimension blocks placement", "A long or wide panel can strand plenty of area in shapes that are too narrow to use."],
      ["Constraints were added late", "Kerf, grain locks, part spacing, or duplicate quantities may turn an area-only fit into a real extra sheet."],
    ],
    [
      ["Largest-part check", "Sort the list by long side and compare the first five parts with the measured usable sheet.", "Any part at or above a usable dimension is the likely blocker.", "Correct the dimension or change the purchasable sheet before optimizing again."],
      ["Area lower bound", "Divide total finished-part area by usable sheet area without rounding down.", "If the result is already near the next whole sheet, kerf and geometry explain the gap.", "Accept the higher planning count or redesign parts before chasing a denser layout."],
      ["Constraint toggle", "Run separate copies with rotation, grain lock, trim, and kerf changed one at a time.", "The first setting that changes sheet count identifies the sensitive assumption.", "Review only the affected parts instead of releasing every constraint."],
      ["Quantity audit", "Expand every quantity into individual parts and compare the count with the drawing.", "An unexpected duplicate or omitted material group creates a false fit problem.", "Correct the source list, version it, and regenerate the layout."],
    ],
    ["Measure one real sheet and enter its usable dimensions.", "Separate materials and thicknesses into independent layouts.", "Lock only parts whose grain or face orientation truly matters.", "Re-run the layout with the measured blade kerf.", "Review the last unplaced part and the shapes of remaining spaces."],
    ["Record usable sheet size instead of relying on the nominal label.", "Keep quantity, material, and grain fields in the source cut list.", "Save a baseline layout before testing constraint changes.", "Reserve contingency for damaged visible panels.", "Review geometry as well as the waste percentage."],
    "Stop cutting if any listed part is larger than the measured usable sheet, the source quantity is unresolved, or the plan fits only when a visible grain rule is ignored.",
    ["/plywood-cut-calculator/", "Test the plywood layout", "/learn/why-plywood-cut-layout-does-not-fit/", "Read the complete fit guide", "/research/plywood-layout-robustness-matrix/", "Compare layout sensitivity"],
  ),
  issue(
    "optimizer-adds-extra-sheet",
    "Layouts",
    "Cut List Optimizer Adds an Extra Sheet: Fix It",
    "a cut list optimizer that adds an extra sheet",
    "A previous layout used fewer sheets, but a small edit or a different optimizer result opens one more sheet.",
    "Treat the extra sheet as a diagnostic signal, not proof that the optimizer failed. Find the part or constraint that crosses the packing threshold, then decide whether the design, stock size, or purchasing plan should change.",
    [
      ["Threshold part", "One added or enlarged rectangle may no longer fit in the remaining usable spaces."],
      ["Different assumptions", "Trim, kerf, spacing, rotation, and stock size may not match the earlier run."],
      ["Heuristic variation", "Two valid packing methods can produce different layouts without either proving a global optimum."],
    ],
    [
      ["Compare inputs", "Export both lists and compare dimensions, quantities, material codes, stock size, kerf, trim, and rotation.", "Any changed field can explain the extra sheet.", "Make the assumptions identical before comparing algorithms."],
      ["Remove-last-change test", "Undo only the newest part or dimension change and regenerate.", "If sheet count drops, that edit crossed the packing threshold.", "Redesign that part or accept the documented purchase change."],
      ["Last-sheet inspection", "List every part on the final sheet and look for one dominant rectangle.", "A nearly empty last sheet often reveals the blocking part.", "Try another allowed stock size or a legitimate seam only after design review."],
      ["Multi-run review", "Run the same input again and, if available, compare another placement mode.", "Stable sheet count with different offcuts suggests the count is robust.", "Choose the safer cut sequence and more useful offcuts rather than a prettier preview."],
    ],
    ["Freeze and label the earlier input.", "Diff the two cut lists field by field.", "Identify the parts assigned to the new sheet.", "Test only legitimate rotation or stock-size alternatives.", "Document why the purchasing count changed."],
    ["Version every released cut list.", "Save stock, trim, kerf, and rotation with the project.", "Compare complete inputs rather than screenshots.", "Review sheet-count sensitivity before quoting material.", "Keep a recovery plan for high-cost visible parts."],
    "Stop if the lower sheet count requires deleting a real part, changing a finished dimension without approval, or rotating a directional panel against its grain rule.",
    ["/apps/cutlist/", "Re-run the saved project", "/learn/cut-list-version-control-guide/", "Control cut-list versions", "/research/plywood-layout-robustness-matrix/", "See robustness tests"],
  ),
  issue(
    "plywood-waste-stays-high",
    "Layouts",
    "Plywood Waste Stays High: Diagnose the Layout",
    "a plywood layout with high waste",
    "The optimizer completes the layout, yet the reported yield remains low or the offcuts are awkward and hard to reuse.",
    "High waste is often structural: large-part geometry, grain locks, mixed material groups, or unusable strip shapes. Diagnose which constraint creates the waste before resizing real parts or accepting a misleading percentage improvement.",
    [
      ["Large-part geometry", "Wide panels can leave long narrow spaces that smaller parts cannot use."],
      ["Over-constrained rotation", "Locking hidden parts can prevent useful placements without protecting appearance."],
      ["Misleading waste metric", "Remaining area may be large but fragmented, while one clean offcut can be more valuable than a higher yield."],
    ],
    [
      ["Shape audit", "Group the empty regions into reusable rectangles and narrow strips.", "Mostly narrow strips indicate a geometry problem, not simply too few parts.", "Change cut sequence or stock size while keeping finished parts unchanged."],
      ["Grain classification", "Mark each part visible, structural-directional, or free to rotate.", "Hidden free-rotation parts reveal unnecessary constraints.", "Release only verified parts and regenerate."],
      ["Material grouping", "Check that backs, drawer bottoms, and different thicknesses are not mixed with case parts.", "Mixed groups can make yield look better while creating an impossible purchase plan.", "Optimize each purchasable material separately."],
      ["Alternative sheet test", "Compare standard and supplier-available sheet sizes using the same parts.", "A different stock geometry may reduce fragments even when area barely changes.", "Choose the option with real availability and manageable handling."],
    ],
    ["Classify usable offcuts by minimum shop size.", "Separate every purchasable material group.", "Review grain locks part by part.", "Compare one legitimate alternative stock size.", "Choose the plan by cut safety and reusable remnants, not yield alone."],
    ["Define an offcut policy before optimization.", "Label visible and free-rotation parts in the source list.", "Keep thin backs and doors in their own material groups.", "Track actual remnants after cutting.", "Compare predicted and actual yield on repeated work."],
    "Stop if the proposed improvement mixes materials, violates grain direction, creates unsafe narrow rips, or assumes offcuts are usable without checking their dimensions.",
    ["/wood-waste-calculator/", "Estimate material waste", "/learn/how-to-reduce-plywood-waste/", "Reduce plywood waste", "/research/plywood-project-yield-benchmarks/", "Compare project yields"],
  ),
  issue(
    "offcuts-too-fragmented",
    "Layouts",
    "Plywood Offcuts Are Too Fragmented: What to Change",
    "plywood offcuts that are too fragmented to reuse",
    "The sheet-count result looks acceptable, but leftover material is split into narrow strips and small islands.",
    "Optimize for offcut shape as a second objective. Preserve one or two rectangular remnants, even if the displayed waste percentage is unchanged, and reject arrangements that create unsafe or unlabelable fragments.",
    [
      ["Single-objective packing", "A layout can minimize opened sheets without valuing the shape of the remainder."],
      ["Small parts fill the wrong zones", "Scattering small rectangles can break a useful remnant into many pieces."],
      ["Cut sequence ignored", "A theoretical remnant may disappear after trimming and crosscuts."],
    ],
    [
      ["Remnant rectangle test", "Draw the largest clean rectangle left on each sheet after all kerfs.", "If no remnant meets the shop minimum, the offcut is functionally scrap.", "Repack small parts to consolidate empty space."],
      ["Small-part grouping", "Highlight parts that could share a strip or be cut from existing stock.", "Scattered small parts are fragmenting the sheet.", "Group them into a deliberate zone or separate remnant workflow."],
      ["Cut-order simulation", "Trace the first breakdown cuts and label what remains after each one.", "A trapped or unsupported remnant is not realistically reusable.", "Change the breakdown direction or preserve a supported rectangle."],
      ["Storage fit", "Compare remnants with the actual rack, label system, and minimum retained size.", "Pieces the shop will not store should not be counted as valuable yield.", "Apply a consistent keep-or-discard threshold."],
    ],
    ["Define the minimum reusable length and width.", "Consolidate small parts on one edge of the layout.", "Simulate the first three breakdown cuts.", "Preserve a rectangular labeled remnant.", "Record the remnant in inventory after cutting."],
    ["Maintain a visible offcut rack.", "Use consistent size labels.", "Plan small recurring parts around available remnants.", "Review offcut shape during layout approval.", "Discard unsafe narrow pieces instead of inflating reuse claims."],
    "Stop if saving an offcut requires an unsupported cut, retaining a dangerously narrow strip, or changing a finished project dimension.",
    ["/wood-waste-calculator/", "Check waste and remnants", "/learn/how-to-reduce-plywood-waste/", "Plan reusable offcuts", "/examples/sheet-goods-storage-cart-cut-list/", "See a storage-cart example"],
  ),
  issue(
    "one-sheet-claim-does-not-fit",
    "Layouts",
    "One-Sheet Project Does Not Fit: Verify the Claim",
    "a one-sheet project plan that does not fit",
    "A plan or video says the project uses one sheet, but the listed parts cannot be placed on the sheet you bought.",
    "Verify the claim from the actual parts, not the project label. One-sheet plans often depend on nominal dimensions, omitted backs or doors, zero trim, smaller kerf, allowed rotation, or a different sheet standard.",
    [
      ["Omitted components", "Backs, shelves, drawer parts, test cuts, or replacement allowance may be excluded from the headline."],
      ["Different stock", "The original author may use a different sheet size or full factory edges."],
      ["Unstated rotation", "A visible panel may have been turned across grain to achieve the claim."],
    ],
    [
      ["Parts reconciliation", "Check every drawing component against the published list.", "Missing rectangles make the one-sheet claim incomplete.", "Add them and recalculate the purchasing plan."],
      ["Sheet measurement", "Measure the purchased sheet after damage and intended edge trim.", "A smaller usable rectangle invalidates a nominal fit.", "Use the measured size in the layout."],
      ["Kerf reconstruction", "Count the required cut lines and apply the actual blade kerf.", "A zero-kerf diagram may consume more width than exists.", "Regenerate with measured kerf."],
      ["Orientation review", "Mark the grain arrow and visible face on every panel.", "A fit that depends on forbidden rotation is not build-ready.", "Accept another sheet or redesign the appearance intentionally."],
    ],
    ["Rebuild the list from the drawing.", "Measure usable stock.", "Add kerf and trim.", "Apply grain rules.", "Publish or print the verified sheet count before cutting."],
    ["Treat project-sheet claims as estimates until inputs are visible.", "Keep backs and optional parts explicit.", "Record the exact sheet standard.", "Show kerf and rotation assumptions.", "Budget recovery material for visible panels."],
    "Stop if the only one-sheet arrangement omits a required part, uses negative spacing, or rotates a directional face without approval.",
    ["/plywood-cut-calculator/", "Verify the one-sheet layout", "/learn/why-plywood-cut-layout-does-not-fit/", "Understand geometry limits", "/examples/coffee-table-cut-list/", "Inspect a published example"],
  ),
  issue(
    "large-part-cannot-fit-5x5-sheet",
    "Layouts",
    "Large Part Cannot Fit a 5×5 Sheet: Options",
    "a large plywood part that cannot fit a 5 by 5 sheet",
    "A required panel exceeds one usable dimension of a Baltic birch or other 60 × 60 inch sheet.",
    "Rotation cannot solve a part that exceeds both usable orientations. Confirm the finished size, then choose a larger available panel, redesign with an approved seam, or change construction; never hide the mismatch by clipping the layout.",
    [
      ["Nominal-versus-usable size", "Edge damage and trim can reduce a 60 inch side below the required dimension."],
      ["Part dimension includes no seam strategy", "A monolithic panel may need redesign for smaller stock."],
      ["Wrong material assumption", "The design may have been developed around 4×8 stock and later switched to 5×5."],
    ],
    [
      ["Orientation test", "Compare part length and width with both usable sheet orientations.", "Failure in both orientations proves a geometry mismatch.", "Do not send the part to the optimizer as if it were placeable."],
      ["Finished-size audit", "Trace the dimension back to the assembly and joinery.", "An allowance or duplicated thickness may be inflating it.", "Correct only with drawing approval."],
      ["Supplier check", "List locally available sheet formats in the same grade and thickness.", "A compatible larger sheet may solve the problem without redesign.", "Confirm price, transport, and handling before ordering."],
      ["Seam review", "Ask whether a joint can be supported, hidden, and structurally acceptable.", "An unsupported cosmetic seam is not a valid layout fix.", "Revise the drawing and parts list if the seam is approved."],
    ],
    ["Measure the usable 5×5 sheet.", "Verify the finished part dimension.", "Check available larger stock.", "Engineer any seam before splitting the part.", "Regenerate every affected part and quantity."],
    ["Choose stock format during design.", "Keep usable sheet dimensions with the material code.", "Flag oversize parts before quoting.", "Plan handling for larger panels.", "Version any seam-driven redesign."],
    "Stop when the part exceeds the usable sheet in both orientations or when a proposed seam lacks structural support and design approval.",
    ["/sheet-calculator/", "Compare sheet sizes", "/research/plywood-sheet-size-comparison/", "Review sheet-size effects", "/learn/plywood-sheet-breakdown-for-beginners/", "Check usable sheet planning"],
  ),
  issue(
    "first-cut-leaves-unusable-strip",
    "Layouts",
    "First Plywood Cut Leaves an Unusable Strip: Fix",
    "a first plywood cut that leaves an unusable strip",
    "The layout fits digitally, but the first rip creates a narrow leftover that is difficult to support, label, or reuse.",
    "Re-sequence the breakdown so the first cut creates a stable panel or a deliberate reusable remnant. A valid nesting image is not automatically a safe or efficient saw sequence.",
    [
      ["Packing ignores machine sequence", "Placement geometry may not model how the sheet is supported during breakdown."],
      ["Trim counted in the wrong place", "An edge allowance can turn a reasonable strip into a sliver."],
      ["Small parts occupy the sheet edge", "Early small-part placements can force an awkward first rip."],
    ],
    [
      ["Support check", "Map the first cut onto the real track saw, table saw, or panel saw setup.", "A narrow unsupported side is a handling risk.", "Flip the retained side or change the breakdown direction."],
      ["Strip width calculation", "Subtract edge trim and kerf from the planned leftover width.", "If it falls below the shop minimum, it is not reusable.", "Move the cut line or repack edge parts."],
      ["Sequence trace", "Number every crosscut that follows the first rip.", "Trapped cuts reveal that the preview is not a practical sequence.", "Create larger subpanels before cutting final parts."],
      ["Reference-edge review", "Identify which factory or trimmed edge establishes squareness.", "Losing the reference edge early can spread error.", "Keep a verified edge through the first breakdown steps."],
    ],
    ["Mark the reference edge.", "Choose a stable first subpanel.", "Account for trim and kerf on the leftover side.", "Number the next two cuts.", "Regenerate if the safe sequence changes placement."],
    ["Review first cuts during layout approval.", "Set a minimum retained-strip width.", "Keep track-saw support pieces available.", "Label subpanels immediately.", "Store cut sequence with the project."],
    "Stop when the first cut cannot be fully supported, the narrow side may tip or bind, or the plan removes the only verified reference edge.",
    ["/apps/cutlist/", "Review the saved layout", "/learn/track-saw-sheet-breakdown-workflow/", "Plan sheet breakdown", "/examples/mobile-workbench-cut-list/", "Inspect a shop example"],
  ),
  issue(
    "sheet-count-changes-with-kerf",
    "Layouts",
    "Sheet Count Changes With Kerf: Is That Normal?",
    "a plywood sheet count that changes with saw kerf",
    "Changing the blade width by a small amount causes the optimizer to open or close a whole sheet.",
    "Yes, it can be normal when rows of parts sit near a packing threshold. Measure the actual blade cut, confirm how the tool applies kerf, and test sensitivity before treating the lower sheet count as reliable.",
    [
      ["Repeated-cut accumulation", "A small kerf difference is multiplied across several adjacent parts."],
      ["Near-threshold row", "One row may fit with almost no remaining width at the smaller kerf."],
      ["Kerf model mismatch", "Some diagrams apply spacing between parts, while a real cut sequence may share or add cuts differently."],
    ],
    [
      ["Measure a real cut", "Cut and measure a test slot in the actual material with the actual blade.", "The gap, not the blade label, is the planning kerf.", "Enter the measured value."],
      ["Sensitivity run", "Generate layouts at measured kerf and a small higher recovery value.", "A sheet-count change means the plan is fragile.", "Quote the robust count or preserve contingency."],
      ["Critical row", "Find rows where part widths plus kerfs nearly equal usable sheet width.", "Those rows create the threshold.", "Change placement or approved dimensions rather than understating kerf."],
      ["Cut model review", "Compare the diagram's kerf assumptions with the intended breakdown sequence.", "Different cut grouping can change total material loss.", "Use a conservative model and document it."],
    ],
    ["Measure kerf in project stock.", "Enter usable sheet size.", "Run a higher-kerf sensitivity copy.", "Find the threshold row.", "Choose the count that survives normal variation."],
    ["Record blade and material with each project.", "Replace or service wandering blades.", "Include a recovery margin near thresholds.", "Do not copy kerf blindly between saws.", "Re-run after changing blades."],
    "Stop if the layout fits only with a kerf smaller than the measured test cut or with no allowance for edge cleanup.",
    ["/kerf-calculator/", "Calculate kerf loss", "/learn/saw-kerf-size-for-cut-list/", "Measure saw kerf", "/research/saw-kerf-sheet-count-impact/", "See sheet-count sensitivity"],
  ),
  issue(
    "panel-rotation-breaks-grain-match",
    "Layouts",
    "Panel Rotation Breaks Grain Match: Repair the Plan",
    "a plywood layout that breaks panel grain matching",
    "The optimized arrangement uses fewer sheets, but adjacent doors, fronts, or visible panels no longer share a coherent grain direction or sequence.",
    "Restore visual intent before optimizing cost. Lock the direction and sequence of matched panels, then allow rotation only for hidden or genuinely non-directional parts.",
    [
      ["Global rotation enabled", "The optimizer treats every rectangle as visually interchangeable."],
      ["Sequence not encoded", "Matched fronts may need to remain adjacent on the source sheet."],
      ["Visible faces unmarked", "The list cannot distinguish show panels from internal parts."],
    ],
    [
      ["Face classification", "Mark every part as exterior visible, interior visible, or hidden.", "Unmarked show faces are vulnerable to arbitrary rotation.", "Add face and orientation fields to the list."],
      ["Grain-arrow review", "Draw the installed grain arrow on each visible part.", "Conflicting arrows reveal the broken match.", "Lock the required orientations."],
      ["Sequence map", "Number adjacent doors and drawer fronts in the order they should be cut.", "Nonadjacent placement can break continuous grain.", "Keep the group together on one sheet when required."],
      ["Cost comparison", "Regenerate with the visible group locked and compare sheet count.", "The difference is the real cost of the appearance requirement.", "Approve the tradeoff explicitly."],
    ],
    ["Identify every visible face.", "Add grain arrows and sequence numbers.", "Lock the matched group.", "Release only hidden parts for rotation.", "Print labels that preserve installation order."],
    ["Decide grain intent during design.", "Use group IDs for matched panels.", "Photograph exceptional veneer before cutting.", "Keep labels on until installation.", "Include appearance constraints in quotes."],
    "Stop if visible panels cannot be traced to an approved grain arrow and sequence, even when the sheet count appears better.",
    ["/plywood-cut-calculator/", "Re-run with rotation rules", "/learn/can-you-rotate-plywood-parts/", "Classify rotation", "/research/grain-direction-rotation-sheet-count-impact/", "Measure the tradeoff"],
  ),
  issue(
    "parts-undersized-after-cutting",
    "Cutting",
    "Parts Are Undersized After Cutting: Find the Error",
    "wood parts that are undersized after cutting",
    "Finished pieces repeatedly measure shorter or narrower than the cut list, often by a blade width or a small accumulated amount.",
    "Quarantine the affected parts and trace the error through reference side, line placement, kerf allowance, fence reading, and final trimming. Do not compensate by editing every cut-list dimension.",
    [
      ["Wrong side of the line", "Cutting on the keep side removes a kerf from the finished part."],
      ["Fence or scale offset", "The pointer, tape, or stop may not match the actual tooth path."],
      ["Cumulative trimming", "Repeated cleanup cuts can reduce parts below finished size."],
    ],
    [
      ["Error pattern", "Measure ten affected parts and record the difference from target.", "A consistent kerf-sized loss points to line-side or calibration error.", "Correct the setup before recutting."],
      ["Reference test", "Cut one labeled test piece from a verified edge.", "Different results by orientation reveal an inconsistent reference side.", "Mark the keep side and reference face."],
      ["Fence calibration", "Measure from a selected tooth to the fence and compare with the scale.", "A stable offset identifies calibration drift.", "Calibrate according to the machine procedure."],
      ["Cut-list audit", "Confirm dimensions are finished sizes rather than rough blanks.", "Mixing rough and finished dimensions creates systematic mismatch.", "Separate blank size from final size in the document."],
    ],
    ["Stop production and label affected parts.", "Measure the error pattern.", "Calibrate with a test cut.", "Confirm rough versus finished dimensions.", "Recut only after one first-article part passes inspection."],
    ["Use a first-article check for every setup.", "Mark keep sides and reference faces.", "Calibrate fence pointers regularly.", "Separate rough and finished columns.", "Record the actual blade kerf."],
    "Stop immediately when a first article is below tolerance; do not continue a repeated setup hoping assembly will hide the loss.",
    ["/kerf-calculator/", "Check cut loss", "/learn/saw-kerf-size-for-cut-list/", "Understand kerf placement", "/examples/shop-cabinet-cut-list/", "Review a shop cut list"],
  ),
  issue(
    "repeated-parts-different-sizes",
    "Cutting",
    "Repeated Parts Differ in Size: 10-Minute Check",
    "repeated wood parts that come out different sizes",
    "Shelves, dividers, rails, or drawer parts cut from one list do not stack flush even though they share a nominal dimension.",
    "Compare the parts as a stack, then isolate setup movement, changing reference edges, stop-block deflection, and measurement technique. Repeated parts should be produced from one stable setup whenever possible.",
    [
      ["Fence or stop moved", "Vibration, dust, or weak clamping can change the effective setting."],
      ["Sequential measurement", "Marking each piece independently adds small layout differences."],
      ["Reference-edge variation", "Parts flipped or referenced from rough edges do not share one datum."],
    ],
    [
      ["Stack test", "Align the reference edges of every repeated part and feel the opposite ends.", "A gradual staircase suggests measurement or fence drift.", "Sort, label, and pause the setup."],
      ["Stop security", "Push and pull the stop with moderate hand pressure, then check for packed dust.", "Any movement explains inconsistent length.", "Clean and clamp the stop securely."],
      ["First-versus-last", "Measure the first and last pieces with the same tool and datum.", "A growing difference points to setup drift.", "Recalibrate and make a new first article."],
      ["Squareness check", "Measure both sides and both diagonals of a sample.", "A tapered or out-of-square part can appear different even when one edge matches.", "Correct the crosscut setup and reference edge."],
    ],
    ["Stack and label all repeated parts.", "Check the stop and fence.", "Verify one reference edge.", "Cut a first article and compare it with the list.", "Batch the remaining parts without changing the setup."],
    ["Use stop blocks for repeats.", "Clean contact surfaces.", "Mark reference edges.", "Check the first, middle, and last part.", "Keep a master part only when it is verified and protected."],
    "Stop when stacked parts exceed the project's tolerance or when the stop can move; assembly pressure is not a valid correction for inconsistent case parts.",
    ["/cut-list-calculator/", "Group repeated parts", "/learn/table-saw-repeat-cut-workflow/", "Use a repeat-cut workflow", "/examples/cube-storage-cut-list/", "Inspect repeated dividers"],
  ),
  issue(
    "grain-direction-wrong-after-optimization",
    "Cutting",
    "Grain Direction Is Wrong After Optimization: Fix",
    "wrong grain direction in an optimized cut list",
    "Parts match their numeric dimensions, but plywood face grain, solid-wood long grain, or matched appearance runs the wrong way.",
    "Do not rotate the physical part to hide the error if its installed orientation is fixed. Correct the source orientation rules, identify affected visible parts, and regenerate labels and layouts.",
    [
      ["Length and width were treated as interchangeable", "The optimizer rotated a directional rectangle."],
      ["Grain field missing", "The source list contains dimensions but no orientation intent."],
      ["Installation orientation changed", "A design revision can turn a formerly horizontal part vertical."],
    ],
    [
      ["Installed-arrow check", "Draw the installed grain arrow on the drawing and on each affected part.", "Nonmatching arrows confirm orientation failure.", "Quarantine the parts before machining."],
      ["Source-field check", "Inspect the grain or rotation field for every visible group.", "Blank or globally enabled rotation caused the mismatch.", "Lock only the required groups."],
      ["Revision check", "Compare orientation with the latest elevation and part label.", "A stale layout may predate the design change.", "Regenerate from the current revision."],
      ["Structural review", "Check whether strength, movement, or machining direction also depends on grain.", "The problem may be structural, not only cosmetic.", "Replace the part when orientation matters to performance."],
    ],
    ["Quarantine mismatched parts.", "Mark installed grain arrows.", "Update source rotation rules.", "Regenerate the layout and labels.", "Approve the replacement plan before cutting."],
    ["Add grain arrows at design time.", "Group matched panels.", "Print orientation on labels.", "Review elevations with the cut list.", "Lock released revisions before production."],
    "Stop if a visible or structural part lacks an approved orientation; never optimize sheet count by silently changing grain intent.",
    ["/apps/cutlist/", "Update orientation rules", "/learn/can-you-rotate-plywood-parts/", "Review rotation decisions", "/research/grain-direction-rotation-sheet-count-impact/", "Compare grain-lock cost"],
  ),
  issue(
    "plywood-delaminates-at-cut",
    "Materials",
    "Plywood Delaminates at the Cut: Causes and Fixes",
    "plywood that delaminates while cutting",
    "Veneer layers separate, lift, or tear away at a fresh cut instead of leaving a stable edge.",
    "Pause and determine whether the failure follows a damaged panel, unsupported veneer, blade condition, feed, moisture, or an internal bond defect. Tool setup can reduce tearout, but it cannot repair defective plywood glue lines.",
    [
      ["Panel defect or moisture damage", "Voids and weak glue lines can open under normal cutting forces."],
      ["Dull or unsuitable blade", "High cutting force can pull weak face veneer away from the core."],
      ["Poor support", "Vibration and unsupported fibers increase breakout at the exit side."],
    ],
    [
      ["Panel map", "Inspect sheet edges and tap or flex around the failed zone.", "Repeated separation in one area suggests a material defect.", "Photograph and isolate the sheet for supplier review."],
      ["Blade test", "Make the same cut in a known-good offcut with the current blade.", "Failure across materials points to blade or setup.", "Clean, sharpen, or replace with an appropriate blade."],
      ["Support check", "Verify full support and correct good-face orientation for the tool.", "Breakout limited to the exit side suggests unsupported veneer.", "Add a sacrificial backer or zero-clearance support."],
      ["Moisture comparison", "Look for swelling, staining, or storage exposure.", "Moisture-linked separation is not a layout issue.", "Dry, reject, or replace material according to project requirements."],
    ],
    ["Stop and mark the failure zone.", "Test the blade on known-good stock.", "Improve support and exit-face protection.", "Inspect for panel-wide defects.", "Replace or return material that continues to separate."],
    ["Inspect sheets at delivery.", "Store panels flat and dry.", "Use clean sharp blades.", "Support both sides of the cut.", "Reserve visible parts away from damaged zones."],
    "Stop using the sheet when separation extends beyond surface tearout, repeats along a glue line, or compromises a structural or visible finished part.",
    ["/material-library/", "Review sheet materials", "/learn/plywood-delivery-inspection-guide/", "Inspect plywood deliveries", "/examples/outdoor-storage-box-cut-list/", "Review an exterior-use example"],
  ),
  issue(
    "melamine-chips-while-cutting",
    "Materials",
    "Melamine Chips While Cutting: Diagnose the Setup",
    "melamine that chips while cutting",
    "The coated face shows white or colored chips along one or both sides of the saw cut.",
    "Identify whether chipping is on the entry face, exit face, or both. Then correct blade condition, face orientation, support, scoring, feed, and zero-clearance setup before cutting finished panels.",
    [
      ["Wrong face orientation", "Different saws support the coating differently at blade entry and exit."],
      ["Blade or clearance problem", "A dirty blade and wide throat opening allow brittle coating to fracture."],
      ["No scoring strategy", "The surface breaks ahead of the main tooth path."],
    ],
    [
      ["Chip-side map", "Mark entry and exit faces on a test cut.", "Damage concentrated on one face points to support and blade direction.", "Orient the show face correctly for the tool."],
      ["Blade inspection", "Clean the blade and inspect teeth for damage or unsuitable geometry.", "Chipping on both faces often indicates blade condition.", "Use a sharp blade intended for coated panels."],
      ["Clearance test", "Compare the existing throat or backer with a zero-clearance support.", "Improvement proves fibers needed closer support.", "Use a safe sacrificial backer or insert."],
      ["Scoring sample", "Test a shallow scoring pass on scrap using a controlled guide.", "A cleaner edge shows surface fracture was leading the main cut.", "Adopt the verified two-pass method for finished pieces."],
    ],
    ["Run a labeled scrap test.", "Clean and inspect the blade.", "Support the exit face.", "Confirm show-face orientation.", "Approve one first article before batch cutting."],
    ["Keep coated-panel blades clean.", "Use zero-clearance support.", "Label show faces.", "Plan trim allowance when appropriate.", "Handle and stack panels without edge impact."],
    "Stop when the first article chips beyond the project's edge-band or finish allowance; do not process the whole batch with an unverified setup.",
    ["/material-library/", "Review panel properties", "/learn/melamine-cutting-plan-for-clean-edges/", "Plan clean melamine cuts", "/examples/craft-storage-cabinet-cut-list/", "Inspect a cabinet example"],
  ),
  issue(
    "edge-banding-changes-part-fit",
    "Materials",
    "Edge Banding Changes Part Fit: Correct the Cut List",
    "edge banding that changes cabinet part fit",
    "Doors, shelves, dividers, or panels no longer meet the intended opening after edge banding is applied.",
    "Separate finished size from core size. Decide which edges receive banding, measure the finished band thickness after application, and calculate the substrate dimension from the assembly requirement.",
    [
      ["Finished and core dimensions mixed", "The cut list does not say whether the number includes banding."],
      ["Band thickness assumed", "Nominal tape thickness can differ after adhesive and trimming."],
      ["Wrong edges counted", "Two opposite edges affect a dimension differently from one exposed edge."],
    ],
    [
      ["Edge map", "Mark banded edges on every affected part.", "Unmarked edges make allowance impossible to audit.", "Add an edge code to the source list."],
      ["Coupon measurement", "Band and trim a sample, then measure finished thickness and width.", "The actual buildup may differ from the catalog value.", "Use the finished coupon result."],
      ["Opening math", "Start from required finished size and subtract verified buildup on contributing edges.", "A mismatch identifies the core-size correction.", "Update substrate dimensions, not the opening silently."],
      ["Hardware clearance", "Recheck door gaps, drawer-slide space, shelf fit, and reveals.", "Banding may consume a functional clearance.", "Revise the assembly and document approval."],
    ],
    ["Map every banded edge.", "Measure a finished coupon.", "Recalculate core dimensions.", "Check hardware and reveal clearances.", "Cut and finish one first article."],
    ["Maintain separate core and finished columns.", "Use consistent edge codes.", "Verify each banding product with a coupon.", "Include banding in revision reviews.", "Do not reuse dimensions across different edge products."],
    "Stop if the drawing does not define finished size or if banding changes a hardware clearance that has not been approved.",
    ["/cut-list-calculator/", "Update core dimensions", "/learn/edge-banding-allowance-in-cut-lists/", "Calculate banding allowance", "/examples/base-cabinet-cut-list/", "Review a cabinet list"],
  ),
  issue(
    "shelf-sagging",
    "Materials",
    "Shelf Is Sagging: Diagnose Span, Load, and Edge",
    "a plywood or wood shelf that is sagging",
    "A shelf bows visibly under its expected contents, or doors and drawer fronts reveal a growing curve.",
    "Reduce load or support the shelf immediately, then verify clear span, material, thickness, load distribution, edge reinforcement, and attachment. Replacing the shelf with the same unsupported design repeats the failure.",
    [
      ["Span too long", "Deflection grows quickly as unsupported distance increases."],
      ["Load underestimated", "Books, records, tools, and pantry goods create dense sustained loads."],
      ["Material or edge too flexible", "Panel grade, orientation, moisture, and a weak front edge affect stiffness."],
    ],
    [
      ["Unload test", "Remove contents and measure whether the shelf recovers.", "Permanent set suggests material damage or long-term creep.", "Replace or reinforce after redesign."],
      ["Span measurement", "Measure the clear unsupported distance, not cabinet outside width.", "A larger real span explains excess deflection.", "Add a divider, cleat, or other designed support."],
      ["Load inventory", "Weigh or conservatively estimate actual contents and their distribution.", "Concentrated loads can exceed the original assumption.", "Redistribute or redesign for the real load."],
      ["Section review", "Record thickness, material, grain direction, front edging, and attachment.", "Missing stiffness or weak connections reveal the design gap.", "Choose an appropriate thicker, reinforced, or shorter shelf."],
    ],
    ["Unload and support the shelf.", "Measure clear span and permanent set.", "Inventory the real load.", "Design reinforcement or a shorter span.", "Update every matching shelf in the cut list."],
    ["Specify load and clear span together.", "Use appropriate front-edge reinforcement.", "Avoid wet or damaged material.", "Distribute dense loads.", "Inspect long shelves before loading the cabinet."],
    "Stop loading a shelf that is rapidly deflecting, separating at supports, or carrying valuable or hazardous items below it.",
    ["/wood-weight-calculator/", "Estimate material weight", "/learn/shelf-span-and-plywood-thickness-guide/", "Review shelf span", "/examples/bookshelf-cut-list/", "Inspect a bookshelf example"],
  ),
  issue(
    "track-saw-cut-not-square",
    "Cutting",
    "Track Saw Cut Is Not Square: 7-Point Diagnosis",
    "a track saw cut that is not square",
    "A crosscut or rip made against a guide rail produces panels with mismatched diagonals, tapered width, or an edge that will not register in assembly.",
    "Determine whether the error is rail alignment, splinter-strip offset, sheet support, saw adjustment, or a bad reference edge. Verify with a measured test panel before recutting project parts.",
    [
      ["Rail aligned to an unverified edge", "A perfect parallel cut can copy an existing error."],
      ["Rail moved during the cut", "Dust, insufficient friction, or cable and hose drag can shift alignment."],
      ["Saw or blade deflection", "Bevel adjustment, play, feed pressure, or a dull blade can move the cut."],
    ],
    [
      ["Diagonal test", "Cut a test rectangle and compare its diagonals.", "Different diagonals prove the panel is not square.", "Do not calibrate from only one edge measurement."],
      ["Rail-reference check", "Place a trusted square between the verified reference edge and rail.", "A gap identifies setup alignment error.", "Realign and clamp when needed."],
      ["Movement marks", "Mark rail position at both ends before cutting and inspect afterward.", "Changed marks prove rail shift.", "Clean support, control hose drag, and secure the rail."],
      ["Saw adjustment", "Check bevel lock, base play, blade condition, and plunge action unplugged.", "Mechanical looseness can create a nonvertical or wandering edge.", "Service or adjust according to manufacturer instructions."],
    ],
    ["Identify a verified reference edge.", "Mark and secure the rail.", "Inspect saw adjustment.", "Cut one test rectangle.", "Approve diagonals and width before project parts."],
    ["Maintain a reference-edge mark.", "Keep rail pads clean.", "Manage cord and hose paths.", "Check splinter-strip offset after blade changes.", "Use a first-article square test."],
    "Stop when the rail shifts, the saw base has play, or a test panel fails the project's diagonal tolerance.",
    ["/fraction-calculator/", "Compare diagonal measurements", "/learn/track-saw-sheet-breakdown-workflow/", "Use a track-saw workflow", "/examples/assembly-table-cut-list/", "Review a flat-work example"],
  ),
  issue(
    "table-saw-repeat-cuts-drift",
    "Cutting",
    "Table Saw Repeat Cuts Drift: Find the Cause",
    "table saw repeated cuts that drift in size",
    "A run of nominally identical rips or crosscuts becomes progressively wider, narrower, or less square.",
    "Stop the batch and compare the first, middle, and last pieces. Then check fence locking, stop blocks, reference edges, feed pressure, blade condition, and measurement method before producing a new first article.",
    [
      ["Fence movement", "A fence can lock out of parallel or shift under side pressure."],
      ["Changing reference face", "Warp, debris, or flipping parts changes how stock contacts the fence."],
      ["Blade and feed effects", "Burning, deflection, and inconsistent pressure can alter the edge."],
    ],
    [
      ["Sequence sample", "Stack and measure the first, middle, and last parts.", "Progressive change confirms drift rather than a single bad blank.", "Quarantine the batch and inspect the setup."],
      ["Fence lock test", "Measure front and rear fence distance before and after locking.", "Different readings reveal alignment or locking error.", "Adjust or service the fence."],
      ["Contact-surface check", "Inspect edges for bow and remove dust at the fence and table.", "Intermittent gaps create inconsistent widths.", "Joint or select a reliable reference edge."],
      ["Blade-path review", "Check blade cleanliness, runout indicators, feed rate, and burning.", "Changing cutting force suggests tool or technique instability.", "Correct the blade setup and make a test cut."],
    ],
    ["Stop and label the batch.", "Compare first, middle, and last.", "Verify fence lock and parallelism.", "Clean and confirm the reference edge.", "Approve a new first article."],
    ["Check fence lock before batches.", "Use consistent feed pressure.", "Clean reference surfaces.", "Measure samples through the run.", "Do not use a drifting part as the new master."],
    "Stop when the fence does not lock repeatably, stock loses full contact, or sample parts exceed tolerance.",
    ["/cut-list-calculator/", "Group repeat dimensions", "/learn/table-saw-repeat-cut-workflow/", "Control repeat cuts", "/examples/small-parts-drawer-cabinet-cut-list/", "Inspect repeated parts"],
  ),
  issue(
    "cabinet-box-not-square",
    "Cabinets",
    "Cabinet Box Is Not Square: Diagnose Before Fixing",
    "a cabinet box that is not square",
    "The cabinet diagonals differ, the back will not sit evenly, or doors and drawers reveal a racked opening.",
    "Do not force fronts to hide a racked case. Verify panel dimensions and edge squareness, place the box on a flat reference, compare diagonals, and inspect joinery, clamps, and back installation.",
    [
      ["Panels are not identical or square", "A tapered side or mismatched top and bottom prevents a rectangular case."],
      ["Assembly surface is twisted", "The cabinet can copy a warped bench or uneven floor."],
      ["Joinery or clamping pulled the case", "Unequal dados, screws, or clamp pressure can rack the opening."],
    ],
    [
      ["Diagonal comparison", "Measure both inside diagonals with the same tape tension.", "The longer diagonal identifies the direction of rack.", "Adjust only while joinery allows safe movement."],
      ["Panel stack", "Compare matching sides, top, and bottom edge to edge.", "Mismatch traces the rack to part fabrication.", "Replace or recut outside-tolerance parts."],
      ["Flatness check", "Move the case to a known flat assembly surface and support all corners.", "A changing diagonal indicates external twist.", "Level the assembly supports before fastening the back."],
      ["Joint seating", "Inspect dados, rabbets, screws, glue squeeze-out, and clamp contact.", "A joint held open changes both width and diagonal.", "Clean and reseat before the adhesive cures when safe."],
    ],
    ["Place the case on a flat reference.", "Measure and record both diagonals.", "Compare matching panels.", "Seat joints with even clamp pressure.", "Fasten the verified square back in sequence."],
    ["Cut matching case parts in one setup.", "Check panels before assembly.", "Use a flat assembly surface.", "Measure diagonals before the back locks the case.", "Label reference faces and edges."],
    "Stop if forcing the case would split a joint, if matching panels differ beyond tolerance, or if the assembly surface is not trustworthy.",
    ["/cut-list-calculator/", "Verify case dimensions", "/learn/cabinet-box-cut-list-basics/", "Review cabinet-box parts", "/examples/base-cabinet-cut-list/", "Inspect a base-cabinet example"],
  ),
  issue(
    "cabinet-doors-collide",
    "Cabinets",
    "Cabinet Doors Collide: Check Overlay and Clearances",
    "cabinet doors that collide when opening",
    "Two doors touch each other, hit a wall or filler, or bind against an adjacent appliance during their swing.",
    "Separate alignment from geometry. Confirm the cabinet opening, overlay or inset rule, hinge cup and plate, reveal, filler, adjacent obstruction, and actual swing before trimming doors.",
    [
      ["Overlay math is wrong", "Door width plus overlay can consume the center reveal or side clearance."],
      ["Hinge setup differs", "Plate height, cup location, or adjustment may not match the design."],
      ["Adjacent obstruction omitted", "Walls, pulls, appliances, and perpendicular doors need swing space."],
    ],
    [
      ["Opening and door measure", "Measure the finished opening and both doors at top, middle, and bottom.", "Unequal reveals may come from door size or a racked case.", "Correct the source of the mismatch before trimming."],
      ["Overlay reconstruction", "Calculate installed coverage from hinge side, meeting stile, and required reveal.", "The total may exceed the available opening.", "Revise door size using the chosen hinge system."],
      ["Hardware verification", "Confirm hinge model, plate, cup setback, and adjustment range.", "A substituted component changes swing geometry.", "Use the specified hardware or redesign."],
      ["Full-swing mockup", "Move the door through its full path with pulls and adjacent items represented.", "Late collision reveals missing filler or stop planning.", "Add an approved filler, limiter, or size revision."],
    ],
    ["Check the cabinet is square.", "Measure openings and doors.", "Rebuild overlay and reveal math.", "Verify hinge components.", "Test a full-size swing before modifying the batch."],
    ["Specify hinge model with the cut list.", "Include center and wall reveals.", "Reserve fillers at obstructions.", "Mock perpendicular door interactions.", "Approve one installed door pair first."],
    "Stop if collision involves an appliance, glass, a wall, or unverified hinge geometry; repeated trimming can destroy the required reveal.",
    ["/cabinet-door-calculator/", "Recalculate door sizes", "/learn/cabinet-door-overlay-and-inset-guide/", "Review overlay and inset", "/examples/wall-cabinet-cut-list/", "Inspect a wall-cabinet example"],
  ),
  issue(
    "drawer-box-too-tight",
    "Cabinets",
    "Drawer Box Is Too Tight: Find the Clearance Error",
    "a drawer box that is too tight for its opening",
    "The assembled drawer will not enter the opening, binds on slides, or has insufficient side clearance.",
    "Measure the finished cabinet opening and installed hardware, not the nominal cabinet width. Recalculate drawer outside width from the exact slide requirement and verify box squareness before recutting parts.",
    [
      ["Nominal opening used", "Case thickness, edging, joinery, or a racked cabinet changes the finished opening."],
      ["Slide clearance mismatch", "Side-mount, undermount, and wood runners use different rules."],
      ["Box is out of square", "Correct width at one edge can still bind diagonally."],
    ],
    [
      ["Opening map", "Measure width at front, middle, and back plus both diagonals.", "The smallest width controls fit; diagonal mismatch reveals rack.", "Correct the cabinet before sizing every drawer to a bad opening."],
      ["Hardware identity", "Verify slide brand, model, length, and required clearance from its instructions.", "Substituted slides can invalidate the cut list.", "Use the actual hardware specification."],
      ["Drawer measure", "Measure outside width at top and bottom, front and back.", "Taper or bow can cause localized binding.", "Correct assembly or replace mismatched components."],
      ["Installation check", "Confirm slides are parallel, level, fully seated, and free of protruding fasteners.", "Hardware position can consume the intended clearance.", "Reinstall accurately before changing box size."],
    ],
    ["Remove and identify the hardware.", "Map the finished opening.", "Measure drawer squareness and width.", "Correct slide installation.", "Recalculate and test one drawer box."],
    ["Buy or specify slides before cutting boxes.", "Measure finished openings.", "Use one verified spacer setup.", "Check case square before drawer work.", "Build one first-article drawer."],
    "Stop if the opening is racked, slide identity is unknown, or force is required to seat the drawer.",
    ["/drawer-box-calculator/", "Recalculate drawer clearance", "/learn/drawer-box-cut-list-basics/", "Review drawer-box sizing", "/examples/small-parts-drawer-cabinet-cut-list/", "Inspect a drawer-cabinet example"],
  ),
  issue(
    "drawer-fronts-uneven",
    "Cabinets",
    "Drawer Fronts Are Uneven: Diagnose Gaps and Reveals",
    "drawer fronts with uneven gaps and reveals",
    "The front gaps vary from side to side or top to bottom even though the fronts were cut to the planned dimensions.",
    "Use one cabinet datum to determine whether the case, drawer slides, boxes, or fronts are causing the pattern. Adjust hardware only after confirming the fronts and opening are square and correctly sized.",
    [
      ["Case opening is racked", "Parallel fronts cannot create equal reveals in a non-square opening."],
      ["Slides sit at different heights", "Box position transfers directly to front alignment."],
      ["Fronts or spacers vary", "Small dimension differences accumulate across a stack."],
    ],
    [
      ["Datum-line check", "Mark one level horizontal reference across the cabinet.", "Changing distance to front edges shows box or slide position error.", "Align hardware to the datum."],
      ["Front stack", "Stack all fronts with reference edges aligned.", "Size variation reveals fabrication error.", "Sort or recut before adjustment."],
      ["Opening diagonals", "Measure the overall face opening diagonals.", "Different diagonals mean reveals cannot all be equal by adjustment alone.", "Correct or consciously distribute the visual error."],
      ["Spacer audit", "Measure the reveal spacers and test them at multiple locations.", "Compressed or inconsistent spacers create changing gaps.", "Use rigid verified setup blocks."],
    ],
    ["Verify the cabinet face is square.", "Stack and compare fronts.", "Establish a datum line.", "Align slides and boxes.", "Attach fronts using rigid reveal spacers."],
    ["Cut front sets in one setup.", "Label installed order.", "Use a level datum.", "Keep consistent rigid spacers.", "Approve the whole bank before final fastening."],
    "Stop if the case is significantly racked or front sizes vary; hardware adjustment should not disguise fabrication errors that will return later.",
    ["/drawer-box-calculator/", "Check front dimensions", "/learn/drawer-box-cut-list-basics/", "Review drawer geometry", "/examples/record-cabinet-cut-list/", "Inspect a drawer-front example"],
  ),
  issue(
    "cabinet-filler-too-narrow",
    "Cabinets",
    "Cabinet Filler Is Too Narrow: Recover the Fit",
    "a cabinet filler strip that is too narrow",
    "The planned filler cannot cover the wall variation, clear a door or pull, or provide enough material for scribing.",
    "Do not split the missing width across cabinets without checking the full run. Re-measure the wall and opening, reconstruct the design allowance, and cut a wider scribe blank where the installation requires it.",
    [
      ["Point measurement used", "Walls can taper, bow, and lean across height and depth."],
      ["Scribe allowance omitted", "A finished filler width is not enough stock for fitting an uneven wall."],
      ["Door or pull clearance ignored", "Hardware swing may require more space than the visible gap."],
    ],
    [
      ["Wall map", "Measure the gap at top, middle, bottom, front, and back.", "Variation reveals the minimum blank needed for scribing.", "Use the largest requirement plus an approved fitting allowance."],
      ["Run total", "Add every cabinet, panel, filler, and intended reveal across the installation.", "A total mismatch may be distributed elsewhere, not only at this filler.", "Resolve the run before cutting replacement material."],
      ["Swing test", "Mock the adjacent door and pull through full travel.", "Collision proves the filler has a functional role.", "Preserve the required clearance in the revised design."],
      ["Fastening zone", "Check whether the filler needs blocking, face-frame attachment, or a finished edge.", "A sliver may be impossible to secure cleanly.", "Widen or redesign the attachment deliberately."],
    ],
    ["Map the real wall gap.", "Reconcile the full cabinet run.", "Verify door and pull travel.", "Cut a wider scribe blank.", "Dry-fit before finishing and permanent attachment."],
    ["Take multi-point field measurements.", "Reserve scribe width in the design.", "Include fillers in the cut list.", "Mock door swing at walls.", "Keep matching finish material for recovery."],
    "Stop if the full run does not reconcile or if the filler cannot support required clearances and attachment after scribing.",
    ["/cabinet-cut-list-calculator/", "Recheck the cabinet run", "/learn/cabinet-filler-and-scribe-strip-guide/", "Plan fillers and scribes", "/examples/kitchen-island-cut-list/", "Inspect an installation example"],
  ),
  issue(
    "wall-cabinets-not-level",
    "Cabinets",
    "Wall Cabinets Are Not Level: Find the Reference Error",
    "wall cabinets that are not level",
    "A cabinet run rises, falls, or steps at cabinet joints even though individual boxes appear square.",
    "Establish one verified level datum for the complete run, then distinguish cabinet fabrication error from rail, ledger, fastener, wall, and ceiling variation. Do not reference each cabinet independently to an uneven ceiling.",
    [
      ["Ceiling or floor used as datum", "Building surfaces commonly vary across a run."],
      ["Ledger or rail moved", "Fastening into uneven walls can twist or lower the support."],
      ["Boxes differ", "Unequal case heights or racked cabinets create stepped tops and bottoms."],
    ],
    [
      ["Laser or level datum", "Project one line across the entire run and measure every cabinet corner to it.", "A consistent slope identifies support alignment; isolated errors identify a box or joint.", "Correct from the common datum."],
      ["Case comparison", "Measure cabinet height at both sides and compare diagonals.", "Different case geometry causes joint steps.", "Repair or replace the affected box."],
      ["Rail inspection", "Check fastener points, shims, and contact with the wall.", "A bowed wall can twist an unshimmed rail.", "Shim and fasten into verified structure."],
      ["Joint clamp check", "Inspect face alignment before final screws.", "Cabinets can be level individually but misaligned at the joint.", "Clamp faces to the datum and refasten safely."],
    ],
    ["Set one run-wide level datum.", "Measure every case.", "Verify the rail or ledger.", "Shim wall variation.", "Align and fasten cabinet faces from the datum."],
    ["Survey walls before fabrication.", "Use one installation datum.", "Verify hanging structure.", "Keep labeled shims and fillers.", "Check each cabinet before adding the next."],
    "Stop if fastener structure is unknown, the rail is moving, or a cabinet box is racked enough to compromise doors or attachment.",
    ["/cabinet-cut-list-calculator/", "Recheck cabinet dimensions", "/learn/wall-cabinet-plywood-layout-guide/", "Review wall-cabinet hanging", "/examples/wall-cabinet-cut-list/", "Inspect a wall cabinet"],
  ),
  issue(
    "base-cabinets-uneven-floor",
    "Cabinets",
    "Base Cabinets on an Uneven Floor: Level the Run",
    "base cabinets on an uneven floor",
    "Cabinets rock, countertop support heights differ, or toe-kick and door reveals change along the run.",
    "Find the highest floor point across the full footprint and build the cabinet datum from there. Level and support each cabinet continuously before fastening the run or templating the countertop.",
    [
      ["Low point used as starting height", "Later cabinets cannot be lowered below the floor high point."],
      ["Shims are incomplete", "Point support can twist a case or settle under load."],
      ["Separate cabinet datums", "Leveling each box without a shared line creates joint steps."],
    ],
    [
      ["Floor survey", "Map floor height at front and back of every cabinet location.", "The highest reading establishes the minimum cabinet position.", "Set the run datum above that point."],
      ["Case base check", "Verify bottoms and toe-kick structures are flat and square.", "A twisted base can mimic floor variation.", "Correct the cabinet before shimming."],
      ["Support inspection", "Check shims under structural load paths, not only visible corners.", "Unsupported spans can settle or bow.", "Add durable continuous support as designed."],
      ["Run-line check", "Measure every cabinet top to the common level line.", "Different readings reveal incomplete leveling.", "Correct before joining and countertop measurement."],
    ],
    ["Survey the whole floor footprint.", "Mark the high point.", "Establish one cabinet datum.", "Shim under structural points.", "Recheck the full run before fastening and templating."],
    ["Take floor readings during field measure.", "Design toe-kick and fillers for variation.", "Use stable load-bearing shims.", "Join cabinets only after leveling.", "Do not template countertops early."],
    "Stop if support is temporary, cabinets rock under load, or the countertop datum has not been verified across the full run.",
    ["/cabinet-cut-list-calculator/", "Recheck base cabinet sizes", "/learn/field-measurement-checklist-before-cut-list/", "Improve field measurements", "/examples/base-cabinet-cut-list/", "Inspect a base-cabinet example"],
  ),
  issue(
    "appliance-opening-too-small",
    "Cabinets",
    "Appliance Opening Is Too Small: Diagnose the Gap",
    "a cabinet appliance opening that is too small",
    "A refrigerator, dishwasher, washer, dryer, microwave, or other appliance cannot enter or maintain required clearances.",
    "Use the exact model installation sheet and field dimensions. Identify whether the loss comes from cabinet size, fillers, countertop, floor, wall, trim, service connections, or an unapproved appliance substitution.",
    [
      ["Nominal appliance size used", "Marketing width is not the complete installation envelope."],
      ["Cabinet run consumed clearance", "Panels, fillers, overhangs, and out-of-square walls reduce the opening."],
      ["Model changed", "A substituted appliance may need different ventilation, door, or connection space."],
    ],
    [
      ["Model verification", "Record exact model and revision, then obtain its installation requirements.", "Mismatch with the design model explains changed clearance.", "Redesign from current approved documentation."],
      ["Opening map", "Measure width, height, depth, diagonals, and floor level at multiple points.", "The smallest path controls installation.", "Correct the obstruction, not just the most visible dimension."],
      ["Service envelope", "Locate plug, valve, drain, hose, vent, and required access.", "Connections can reduce usable depth or prevent seating.", "Coordinate service relocation with qualified trades."],
      ["Movement test", "Model door, drawer, lid, and service-removal travel.", "A static fit can still fail in operation.", "Preserve the manufacturer's movement clearances."],
    ],
    ["Confirm the exact appliance model.", "Map the real opening.", "Compare every required clearance.", "Identify cabinet versus service conflicts.", "Approve any redesign before cutting or modifying cabinets."],
    ["Lock appliance models before fabrication.", "Attach cut sheets to the project.", "Measure the installation path.", "Include service and ventilation zones.", "Reverify after substitutions."],
    "Stop when the opening violates manufacturer clearance, ventilation, service, or electrical requirements; do not force the appliance or remove structural cabinet parts casually.",
    ["/cabinet-cut-list-calculator/", "Recheck cabinet dimensions", "/learn/field-measurement-checklist-before-cut-list/", "Capture field dimensions", "/examples/microwave-shelf-cabinet-cut-list/", "Inspect an appliance cabinet"],
  ),
  issue(
    "duplicate-cut-list-rows",
    "Workflow",
    "Duplicate Cut List Rows: Find and Merge Safely",
    "duplicate rows in a woodworking cut list",
    "The same-looking part appears more than once, totals seem inflated, or optimization includes unexpected duplicates.",
    "Do not merge by dimensions alone. Compare part name, material, thickness, grain, edge treatment, finish, and revision; merge rows only when every fabrication requirement is identical.",
    [
      ["Copy-and-paste duplication", "A design revision leaves both old and new rows active."],
      ["Legitimate look-alikes", "Two equal rectangles may use different material, edges, faces, or machining."],
      ["Quantity expansion confusion", "A tool may display grouped input and individual placed parts separately."],
    ],
    [
      ["Exact-key comparison", "Compare normalized name, dimensions, quantity, material, thickness, grain, edge code, and revision.", "Only identical full keys are safe merge candidates.", "Combine quantities and preserve source references."],
      ["Drawing trace", "Locate every row callout in the latest drawing or model.", "Rows with no current callout may be stale.", "Archive them rather than silently deleting evidence."],
      ["Placement check", "Compare grouped input count with individual labels on the layout.", "Expanded placements may look duplicated while representing real quantity.", "Keep the source quantity unchanged."],
      ["Material total", "Recalculate parts per material before and after a proposed merge.", "Unexpected total change reveals a bad merge.", "Restore the source and resolve identifiers."],
    ],
    ["Freeze the current revision.", "Build a full comparison key.", "Trace candidates to the drawing.", "Merge only identical fabrication rows.", "Regenerate totals and layout, then review counts."],
    ["Use stable part IDs.", "Separate material and edge fields.", "Archive old revisions.", "Avoid merging solely by size.", "Run a quantity audit before purchasing."],
    "Stop if two rows share dimensions but differ in any fabrication field or if their source drawing references cannot be reconciled.",
    ["/cut-list-calculator/", "Rebuild grouped rows", "/learn/cut-list-quality-check-before-buying-material/", "Audit the cut list", "/apps/cutlist/", "Save a corrected revision"],
  ),
  issue(
    "revision-dimensions-changed",
    "Workflow",
    "Cut List Dimensions Changed After Revision: Audit",
    "cut list dimensions that changed after a design revision",
    "A current drawing, saved layout, estimate, label set, or shop copy shows different dimensions for the same part.",
    "Declare one released source of truth, compare revisions by stable part ID, and stop production until changed, added, removed, and unchanged parts are reconciled across layouts, labels, and material orders.",
    [
      ["Stale export", "A PDF or printout was created before the latest design change."],
      ["Part renamed", "Name-based comparison treats one changed part as unrelated old and new rows."],
      ["Downstream files not regenerated", "Layout, labels, and purchasing totals can remain on the older version."],
    ],
    [
      ["Revision header", "Check revision ID and timestamp on drawing, cut list, layout, labels, and order.", "Any mismatch identifies stale downstream material.", "Withdraw and regenerate it."],
      ["Stable-ID diff", "Compare old and new rows by part ID rather than display name.", "Changed dimensions and quantities become explicit.", "Create a signed change list."],
      ["Physical status", "Mark affected parts as not cut, cut, machined, assembled, or installed.", "Recovery depends on actual production state.", "Plan replacements and prevent mixed revisions."],
      ["Material impact", "Regenerate sheet count and inventory after the changes.", "A small dimension edit can cross a layout threshold.", "Update purchasing before releasing work."],
    ],
    ["Freeze production copies.", "Choose the released source.", "Diff by stable part ID.", "Map affected physical parts.", "Regenerate layouts, labels, totals, and release notes."],
    ["Put revision IDs on every export.", "Use stable part IDs.", "Archive superseded files.", "Issue change summaries.", "Require shop acknowledgment before resuming."],
    "Stop when any shop document lacks a matching released revision or when affected physical parts have not been identified.",
    ["/apps/cutlist/", "Save the new project revision", "/learn/cut-list-revision-workflow/", "Use a revision workflow", "/learn/cut-list-version-control-guide/", "Control versions"],
  ),
  issue(
    "material-order-missing-parts",
    "Workflow",
    "Material Order Is Missing Parts: Reconcile the List",
    "a material order that is missing cut list parts",
    "The purchase total is lower than the released cut list requires, or a material group has no stock assigned.",
    "Reconcile the order from the released part list by purchasable material group, then add kerf, trim, defects, and recovery policy. Area totals alone cannot prove every rectangle will fit.",
    [
      ["Material code missing", "Unclassified parts can disappear from grouped purchasing totals."],
      ["Optional component assumed", "Backs, doors, shelves, or fillers may be treated differently by design and estimating."],
      ["Area-only conversion", "Total square footage ignores geometry and sheet-size constraints."],
    ],
    [
      ["Unassigned-row filter", "List parts with blank material, thickness, or stock size.", "Any result is absent from a trustworthy order.", "Assign and approve the purchasable group."],
      ["Drawing reconciliation", "Count drawing components against cut-list quantities.", "Missing components expose list incompleteness.", "Add them before recalculating."],
      ["Group layout", "Optimize each material and thickness separately.", "A group may need more sheets than its area lower bound.", "Order from the actual grouped layout."],
      ["Contingency review", "Identify visible, difficult, or defect-sensitive parts.", "No recovery allowance creates a fragile order.", "Add a documented project-specific contingency."],
    ],
    ["Freeze the released list.", "Find unassigned parts.", "Reconcile with the drawing.", "Generate layouts by material group.", "Add approved trim and recovery allowance to the order."],
    ["Require material codes.", "Keep optional parts explicit.", "Generate orders from released revisions.", "Use geometry-based sheet counts.", "Record purchase and offcut inventory."],
    "Stop ordering if any part lacks a material assignment, the released revision is unclear, or sheet count is based only on total area.",
    ["/material-list-generator/", "Rebuild the material list", "/learn/cut-list-quality-check-before-buying-material/", "Run a pre-purchase audit", "/examples/", "Compare complete examples"],
  ),
  issue(
    "mixed-units-in-cut-list",
    "Workflow",
    "Mixed Units in a Cut List: Prevent Costly Errors",
    "mixed inch and millimeter units in a cut list",
    "Some dimensions appear plausible but are off by a conversion factor, decimal placement, or fraction interpretation after files are combined.",
    "Choose one working unit per released list, preserve the original value and unit during conversion, and validate suspicious dimensions against the drawing and stock before optimization or cutting.",
    [
      ["Unit column omitted", "A bare number is interpreted by software or a person using the wrong convention."],
      ["Rounded conversion reused", "Converting back and forth can accumulate error."],
      ["Fraction parsed as decimal", "A value such as 3/8 can be entered or imported incorrectly."],
    ],
    [
      ["Range scan", "Sort dimensions and flag implausibly small or large values for the project.", "Outliers often reveal a unit mismatch.", "Trace them to the original source."],
      ["Unit-field audit", "Require a unit for every imported group.", "Blank or mixed fields make the list ambiguous.", "Normalize in a controlled copy."],
      ["Conversion sample", "Manually verify several converted values with sufficient precision.", "Mismatch identifies a formula or rounding problem.", "Correct the conversion rule before bulk use."],
      ["Stock comparison", "Compare the largest parts with actual stock in the same unit.", "Impossible ratios reveal wrong interpretation.", "Stop optimization and correct the source."],
    ],
    ["Freeze the imported list.", "Label every source unit.", "Choose one working unit.", "Verify conversion samples.", "Recheck critical dimensions against drawings and stock."],
    ["Store units with values.", "Avoid repeated round-trip conversion.", "Define precision and rounding once.", "Label shop documents clearly.", "Use a first-article measurement before batch work."],
    "Stop if any critical dimension has no traceable source unit or if a converted part does not make physical sense against the stock.",
    ["/inch-mm-converter/", "Verify unit conversions", "/learn/cut-list-review-before-cutting-guide/", "Review before cutting", "/apps/cutlist/", "Save a normalized list"],
  ),
  issue(
    "labels-do-not-match-parts",
    "Workflow",
    "Cut List Labels Do Not Match Parts: Recover Safely",
    "cut list labels that do not match physical parts",
    "Physical panels, printed labels, and layout identifiers disagree, making assembly order and machining requirements uncertain.",
    "Pause machining and reconstruct identity from dimensions, material, grain, edge treatment, face quality, and revision. Do not relabel by size alone when look-alike parts have different requirements.",
    [
      ["Labels applied out of sequence", "Sorted physical parts no longer match the placement order."],
      ["Revision mismatch", "Labels came from a different list than the cut layout."],
      ["Nonunique names", "Several parts share generic labels such as shelf or side."],
    ],
    [
      ["Revision check", "Compare label revision with the active cut list and layout.", "Different IDs invalidate direct matching.", "Withdraw the stale label set."],
      ["Physical signature", "Record each unknown part's dimensions, material, grain, banded edges, and visible face.", "The combined signature narrows identity safely.", "Match against all source fields."],
      ["Quantity balance", "Count identified and unknown parts for each part ID.", "Overages and shortages expose swaps.", "Resolve the complete set before machining."],
      ["Drawing placement", "Place candidate IDs on the assembly drawing.", "Impossible orientation or machining reveals a wrong match.", "Keep the part quarantined."],
    ],
    ["Pause machining.", "Collect the active source documents.", "Build physical signatures.", "Balance quantities by stable ID.", "Apply new durable labels only after full reconciliation."],
    ["Use unique part IDs.", "Print revision and grain arrows.", "Label immediately after cutting.", "Keep labels through finishing.", "Separate batches physically by project and material."],
    "Stop when two candidate identities remain plausible or when revision, grain, or edge requirements cannot be recovered confidently.",
    ["/apps/cutlist/", "Reopen the saved layout", "/learn/cut-list-labeling-system/", "Build a labeling system", "/examples/", "Compare visible part lists"],
  ),
  issue(
    "cut-list-missing-hardware-clearance",
    "Workflow",
    "Cut List Misses Hardware Clearance: Audit the Parts",
    "a cut list missing hardware clearances",
    "Parts match the cabinet drawing but interfere with slides, hinges, fasteners, lifts, pulls, brackets, or access for installation.",
    "Attach exact hardware to the design, map its installation and movement envelope, then recalculate only the affected finished parts. Hardware clearance belongs upstream of optimization.",
    [
      ["Generic hardware assumed", "Different models use different setbacks, gaps, drilling, and movement."],
      ["Static envelope only", "A component may fit at rest but collide during opening or adjustment."],
      ["Fastener and tool access omitted", "Installation needs room beyond the final hardware body."],
    ],
    [
      ["Hardware identity", "Record manufacturer and exact model for every affected assembly.", "Missing identity makes clearance unprovable.", "Obtain current instructions before redesign."],
      ["Envelope mockup", "Trace the component through full movement and adjustment.", "Collision reveals which part or filler controls the space.", "Revise the assembly deliberately."],
      ["Installation access", "Check driver, drill, screw, clip, and release access.", "A final fit without installation access is not buildable.", "Add access or change sequence."],
      ["Affected-part map", "List every part whose dimension, machining, or edge changes.", "Partial updates create mixed geometry.", "Regenerate the complete affected set."],
    ],
    ["Identify exact hardware.", "Review installation instructions.", "Mock static and moving envelopes.", "Map every affected part.", "Revise and regenerate the released cut list."],
    ["Select hardware before final sizing.", "Attach specs to the project.", "Include access and adjustment zones.", "Prototype unfamiliar hardware.", "Review substitutions as design changes."],
    "Stop if hardware identity is unknown, instructions conflict with the design, or safe installation and service access are not available.",
    ["/apps/cutlist/", "Update the project parts", "/learn/cut-list-review-before-cutting-guide/", "Review fabrication inputs", "/templates/drawer-box-cut-list/", "Start from a hardware-aware template"],
  ),
  issue(
    "cabinet-back-will-not-fit",
    "Cabinets",
    "Cabinet Back Will Not Fit: Check the Construction",
    "a cabinet back panel that will not fit",
    "The back is too large, too small, or prevents the cabinet from reaching square during assembly.",
    "Confirm whether the back is applied, captured, rabbeted, or set into a groove. Then measure the actual case and joinery, not nominal outside dimensions, before correcting the panel.",
    [
      ["Construction method changed", "An applied back and captured back require different dimensions."],
      ["Joinery depth differs", "Groove or rabbet position and depth alter the panel envelope."],
      ["Case is racked", "A square back cannot seat in a non-square opening."],
    ],
    [
      ["Method confirmation", "Mark the intended back construction on the current drawing.", "Ambiguity explains inconsistent dimension formulas.", "Choose and release one method."],
      ["Case diagonals", "Square the case and compare its diagonals before fitting the back.", "A racked opening can mimic an oversize panel.", "Correct the case first."],
      ["Joinery map", "Measure groove or rabbet distance, width, depth, and corner conditions.", "Actual joinery may not match the cut list allowance.", "Recalculate from the measured geometry."],
      ["Panel square", "Measure both dimensions at several points and compare diagonals.", "A tapered panel will not seat consistently.", "Recut from a verified reference edge."],
    ],
    ["Confirm the back method.", "Square the case.", "Measure actual joinery.", "Calculate the panel envelope.", "Dry-fit before glue and permanent fastening."],
    ["Specify back construction in templates.", "Cut grooves in one setup.", "Check case square early.", "Keep backs separated by thickness.", "Dry-fit before the adhesive clock starts."],
    "Stop if the case is not square or the back construction method is unresolved; trimming the panel can lock a fabrication error into the cabinet.",
    ["/cut-list-calculator/", "Recalculate the back", "/learn/cabinet-box-cut-list-basics/", "Review back construction", "/examples/shop-cabinet-cut-list/", "Inspect a cabinet example"],
  ),
  issue(
    "plywood-edge-trim-removes-fit",
    "Materials",
    "Plywood Edge Trim Removes the Fit: Recalculate",
    "plywood edge trim that makes a layout stop fitting",
    "A layout fits on nominal sheet dimensions but fails after damaged or non-square factory edges are trimmed.",
    "Enter the measured usable rectangle after planned edge cleanup. If the sheet count changes, the original layout was sensitive to nominal edges and should not be released without a robust alternative.",
    [
      ["Trim omitted", "The optimizer uses the full label size while the shop removes material on multiple edges."],
      ["Sheet out of square", "Squaring one edge can reduce usable length differently across the panel."],
      ["Layout at threshold", "Rows use nearly all nominal width with no recovery margin."],
    ],
    [
      ["Usable rectangle", "Measure the largest square clean rectangle inside the sheet.", "It may be smaller than nominal in both directions.", "Use those dimensions for the layout."],
      ["Trim policy", "Define which edges are trimmed and by how much before placement.", "Inconsistent assumptions create shop surprises.", "Store the policy with the material group."],
      ["Sensitivity run", "Compare zero trim with expected and higher trim scenarios.", "A sheet-count jump reveals fragility.", "Quote the robust scenario or inspect every sheet."],
      ["Critical-part check", "Identify parts placed against trimmed boundaries.", "They are most likely to lose fit.", "Move them or reserve cleaner stock."],
    ],
    ["Inspect the delivered sheet.", "Define a usable rectangle.", "Enter trim before nesting.", "Run a higher-trim sensitivity test.", "Reserve clean stock for critical visible panels."],
    ["Create a supplier-specific trim policy.", "Inspect at delivery.", "Do not place critical parts on uncertain edges.", "Keep recovery allowance near thresholds.", "Record actual usable dimensions."],
    "Stop when the layout relies on damaged factory edges or when the measured usable rectangle is smaller than any required part.",
    ["/plywood-cut-calculator/", "Enter usable sheet size", "/learn/plywood-edge-trim-allowance-guide/", "Plan edge trim", "/research/edge-trim-allowance-impact/", "See trim sensitivity"],
  ),
  issue(
    "cut-list-quantity-wrong",
    "Workflow",
    "Cut List Quantity Is Wrong: Audit Before Cutting",
    "a cut list with the wrong part quantity",
    "The layout shows too few or too many shelves, dividers, rails, doors, or repeated pieces compared with the drawing.",
    "Stop production and reconcile quantities from assemblies, not visual similarity. Separate per-unit quantity from number of units, optional components, handed parts, and replacement allowance.",
    [
      ["Multiplier missed", "A per-cabinet list was not multiplied by the number of cabinets."],
      ["Nested assemblies overlooked", "Each drawer, door, or bay contributes its own repeated parts."],
      ["Left and right collapsed", "Handed parts may share dimensions but require different machining or faces."],
    ],
    [
      ["Assembly tree", "List project units, subassemblies, and parts with quantity at each level.", "A missing multiplier becomes visible.", "Recalculate the expanded total."],
      ["Drawing callouts", "Count every occurrence of the part ID in current drawings.", "Mismatch identifies a source-list error.", "Correct the released list."],
      ["Handing check", "Separate left, right, face, grain, and machining variants.", "Equal rectangles may not be interchangeable.", "Keep distinct IDs even when dimensions match."],
      ["Layout count", "Count placed labels and compare with expanded quantity.", "A generator or filter may have dropped a group.", "Regenerate and validate before purchase."],
    ],
    ["Pause the affected batch.", "Build the assembly tree.", "Trace drawing callouts.", "Separate handed variants.", "Regenerate layouts, labels, and material totals."],
    ["Use stable part IDs.", "Store per-unit and project totals.", "Keep optional parts explicit.", "Run a quantity balance before purchase.", "Check physical counts after each batch."],
    "Stop if the expanded assembly quantity does not equal both drawing callouts and layout placements.",
    ["/cut-list-calculator/", "Rebuild part quantities", "/learn/cut-list-quality-check-before-buying-material/", "Audit quantities", "/examples/", "Compare complete part lists"],
  ),
];

const expectedCount = 35;
const categories = new Set(troubleshootingIssues.map((entry) => entry.category));
const requiredCategories = ["Layouts", "Cutting", "Cabinets", "Materials", "Workflow"];

if (troubleshootingIssues.length !== expectedCount) {
  throw new Error(`Expected ${expectedCount} troubleshooting issues, received ${troubleshootingIssues.length}`);
}
if (new Set(troubleshootingIssues.map((entry) => entry.slug)).size !== expectedCount) {
  throw new Error("Troubleshooting slugs must be unique");
}
if (new Set(troubleshootingIssues.map((entry) => entry.title)).size !== expectedCount) {
  throw new Error("Troubleshooting titles must be unique");
}
for (const category of requiredCategories) {
  if (!categories.has(category)) throw new Error(`Missing troubleshooting category: ${category}`);
}
for (const entry of troubleshootingIssues) {
  if (entry.causes.length < 3 || entry.checks.length < 4 || entry.fixSteps.length < 5 || entry.prevention.length < 5) {
    throw new Error(`Troubleshooting entry is too shallow: ${entry.slug}`);
  }
  if (entry.links.length !== 6) throw new Error(`Expected three related links for ${entry.slug}`);
}
