const makeCategory = ({ slug, name, description, stage, baseFields, links, topics }) => ({
  slug,
  name,
  description,
  stage,
  baseFields,
  links,
  topics: topics.map(([topicSlug, title, summary, outcome, checklistSlug, focusFields]) => ({
    slug: topicSlug,
    title,
    summary,
    outcome,
    checklistSlug,
    focusFields,
  })),
});

export const worksheetPublishedDate = "2026-07-26";

export const worksheetCategories = [
  makeCategory({
    slug: "measurements-site-survey",
    name: "Measurements & Site Survey",
    description: "Capture controlling dimensions, datums, access limits, obstructions, and field conditions before shop work begins.",
    stage: "during site survey, design verification, or final field measurement",
    baseFields: [
      ["Project and location", "Name the project, room, elevation, or assembly this record controls.", "Kitchen / north wall"],
      ["Revision and survey date", "Record the drawing revision and the date the physical condition was measured.", "Rev C / 2026-07-26"],
      ["Datum, units, and precision", "State the origin, working unit, and smallest increment used for every dimension.", "Finished left wall / mm / nearest 1 mm"],
      ["Measured by and tool", "Identify the person and measuring device so the method can be repeated.", "A. Lee / laser plus steel tape"],
    ],
    links: [
      ["/checklists/jobsite-measurement-release/", "Jobsite measurement release", "Checklist"],
      ["/learn/field-measurement-checklist-before-cut-list/", "Field measurement workflow", "Learn"],
      ["/inch-mm-converter/", "Inch and millimeter converter", "Calculator"],
    ],
    topics: [
      ["room-dimension-survey", "Room Dimension Survey Worksheet", "Record wall lengths, ceiling heights, diagonals, floor variation, and fixed room references before planning built-ins or cabinets.", "Produce one traceable room envelope that distinguishes nominal dimensions from the smallest usable opening.", "jobsite-measurement-release", [
        ["Wall dimensions", "Measure each controlling wall at low, middle, and high positions.", "North wall: 3658 / 3655 / 3652 mm"],
        ["Ceiling and floor profile", "Record height at both ends and every major change in level.", "2412 mm left; 2405 mm right"],
        ["Room diagonals", "Measure both diagonals from the same finished corners.", "A-C 5124 mm; B-D 5113 mm"],
        ["Fixed references", "Locate doors, windows, utilities, trim, and changes of plane from the datum.", "Outlet center 812 mm from left datum"],
      ]],
      ["cabinet-opening-measurement", "Cabinet Opening Measurement Worksheet", "Measure cabinet openings for doors, drawers, shelves, appliances, and inserts with top, middle, bottom, and diagonal checks.", "Create an opening record that supports worst-case clearance instead of relying on one center measurement.", "opening-clearance-verification", [
        ["Opening width profile", "Measure clear width at the top, middle, and bottom.", "762 / 760 / 758 mm"],
        ["Opening height profile", "Measure clear height at the left, center, and right.", "718 / 717 / 715 mm"],
        ["Diagonal and square check", "Record both diagonals and the direction of any rack.", "904 / 899 mm; low at right"],
        ["Hardware and movement zone", "Record hinge, slide, pull, and removal clearances around the opening.", "110° hinge; 35 mm pull projection"],
      ]],
      ["appliance-opening-measurement", "Appliance Opening Measurement Worksheet", "Reconcile the physical appliance, manufacturer requirements, utilities, ventilation, and cabinet opening before parts are released.", "Connect the real product envelope and service requirements to the cabinet dimensions that will be cut.", "appliance-opening-release", [
        ["Product identification", "Record manufacturer, model, revision, and whether the physical unit was checked.", "ExampleCo DW-24 / unit on site"],
        ["Required and actual opening", "List required minimums beside measured width, height, and depth.", "Req 610 W; actual 615 mm"],
        ["Utilities and connectors", "Locate power, water, drain, gas, vent, and connector projections.", "Drain center 180 mm from left"],
        ["Door, service, and removal path", "Trace full operation plus future service and replacement access.", "Door clears pull by 22 mm"],
      ]],
      ["built-in-wall-survey", "Built-In Wall Survey Worksheet", "Map wall bow, plumb, floor level, ceiling variation, baseboard, outlets, and scribe conditions for fitted furniture.", "Turn an irregular wall into explicit scribe, filler, leveling, and service allowances.", "square-level-plumb-survey", [
        ["Wall bow profile", "Measure offset from a straight reference at regular stations.", "0 / +5 / +9 / +3 mm"],
        ["Plumb at contact planes", "Check wall lean at front and back cabinet contact lines.", "Top leans in 7 mm"],
        ["Floor and ceiling control points", "Map high and low points across the full run.", "Floor high point at 1820 mm"],
        ["Trim and service conflicts", "Record baseboard, casing, outlets, vents, and access panels.", "Baseboard 19 × 140 mm"],
      ]],
      ["stair-opening-field-measurement", "Stair Opening Field Measurement Worksheet", "Capture total rise, available run, landing, opening, headroom controls, framing, and finish assumptions before stair layout.", "Preserve the field geometry and finish references needed for a qualified stair design review.", "final-design-release", [
        ["Finished total rise", "Measure between finished floor reference planes and state unfinished allowances.", "2784 mm finished floor to floor"],
        ["Available run and landing", "Record clear horizontal space and landing boundaries.", "Run limit 3260 mm"],
        ["Opening and headroom controls", "Locate opening edges, beams, ceilings, and sloped obstructions.", "Header underside at 2140 mm"],
        ["Structure and finish assumptions", "Record framing information, tread finish, nosing, and responsible designer.", "18 mm finish; engineer review pending"],
      ]],
      ["door-window-obstruction-survey", "Door, Window & Obstruction Survey Worksheet", "Locate openings, casing, swings, sills, handles, outlets, pipes, vents, and other keep-out zones from shared datums.", "Create a coordinate record that prevents a cabinet or panel from covering, colliding with, or trapping an obstruction.", "opening-clearance-verification", [
        ["Opening coordinates", "Record left, right, top, and bottom edges from the project datums.", "Window left 1240 mm; sill 935 mm"],
        ["Trim projection", "Measure casing, stool, apron, baseboard, and other surface projections.", "Casing projects 18 mm"],
        ["Movement envelope", "Record door, window, latch, handle, and cleaning movement.", "Door arc reaches 865 mm"],
        ["Service keep-out zone", "Define required access around electrical, plumbing, ventilation, or controls.", "Panel requires 760 mm clear"],
      ]],
      ["delivery-path-measurement", "Delivery Path Measurement Worksheet", "Measure doors, elevators, stairs, corners, ceiling restrictions, and staging space against the largest finished assembly.", "Prove whether the project can be delivered assembled or must be divided for site assembly.", "delivery-load-in-release", [
        ["Largest assembly envelope", "Record finished length, width, height, weight estimate, and fragile projections.", "2180 × 920 × 610 mm"],
        ["Minimum clear opening", "Measure the narrowest door, gate, or elevator opening with hardware considered.", "Door clear width 812 mm"],
        ["Turns and vertical restrictions", "Record corner radii, stair landings, handrails, and ceiling drops.", "Landing depth 980 mm"],
        ["Staging and protection", "Identify unload location, floor protection, temporary storage, and lifting needs.", "Two-person carry; padded staging"],
      ]],
      ["square-level-plumb-record", "Square, Level & Plumb Record Worksheet", "Document diagonal, level, and plumb observations for an opening, cabinet run, wall, or installed assembly.", "Keep the measured direction and magnitude of variation available for layout, fitting, and acceptance.", "square-level-plumb-survey", [
        ["Diagonal comparison", "Record both diagonals and identify which corner is displaced.", "D1 1824; D2 1817 mm"],
        ["Level readings", "Record high point, low point, total variation, and distance.", "High at left; 8 mm over 2400"],
        ["Plumb readings", "Record lean at each controlling plane and height.", "Wall out 6 mm at 2100"],
        ["Adjustment allocation", "Assign variation to fillers, scribes, shims, reveals, or upstream correction.", "4 mm scribe plus 4 mm shim"],
      ]],
      ["template-mockup-dimension", "Template & Mockup Dimension Worksheet", "Record a physical template's orientation, scale, reference edges, contact points, allowances, approval, and transfer method.", "Make a site-fitted template reproducible in the shop without flipping it or guessing what its edge represents.", "mockup-template-approval", [
        ["Template identity and material", "Name the template and record its material, thickness, and stability.", "Fireplace left return / 6 mm MDF"],
        ["Orientation and reference edges", "Mark face, top, room, origin, and no-flip instructions.", "Room face / top arrow / left datum"],
        ["Edge meaning and allowance", "State whether each edge is finished size, rough size, centerline, or offset.", "Scribe edge includes 12 mm trim"],
        ["Fit and approval evidence", "Record test location, gaps, photos, approver, and date.", "Photo T-14 / approved by M. Chen"],
      ]],
      ["final-field-verification", "Final Field Verification Worksheet", "Recheck controlling site dimensions immediately before fabrication, delivery, or installation and reconcile every change.", "Issue a final measured baseline with differences, owners, and downstream updates clearly identified.", "final-design-release", [
        ["Controlling dimensions rechecked", "List each dimension that can change parts, fit, or access and its latest value.", "Run width now 3648 mm"],
        ["Change from prior survey", "Show previous value, current value, variance, and reason when known.", "−7 mm after wall finish"],
        ["Affected outputs", "Name drawings, cut lists, orders, labels, and installation plans that need revision.", "Revise fillers F1/F2 and PO line 4"],
        ["Release or hold decision", "Record approver, release scope, unresolved conditions, and hold points.", "Boxes released; fronts held"],
      ]],
    ],
  }),
  makeCategory({
    slug: "cut-list-material-planning",
    name: "Cut List & Material Planning",
    description: "Translate finished project requirements into parts, stock groups, purchasing units, allowances, and traceable layout assumptions.",
    stage: "while preparing cut lists, material takeoffs, purchase orders, or layout inputs",
    baseFields: [
      ["Project and active revision", "Identify the exact project revision that supplies the quantities and dimensions.", "Mudroom lockers / Rev B"],
      ["Prepared and reviewed by", "Record the author, independent reviewer, and review date.", "Prepared AL / reviewed KC"],
      ["Units and rounding rule", "State working units, conversion source, and purchasing rounding convention.", "Inches / nearest 1/16 / full sheets"],
      ["Source documents", "List drawings, schedules, templates, and manufacturer data used.", "A201, cabinet schedule, hinge sheet"],
    ],
    links: [
      ["/checklists/purchase-reconciliation/", "Purchase reconciliation", "Checklist"],
      ["/learn/material-groups-to-purchase-list/", "Material groups to purchase list", "Learn"],
      ["/plywood-cut-calculator/", "Plywood cut calculator", "Calculator"],
    ],
    topics: [
      ["cut-list-input", "Cut List Input Worksheet", "Collect part IDs, quantities, finished sizes, materials, grain, edge treatment, and notes before optimization.", "Create a complete rectangular-part input set that can be audited before any layout is trusted.", "cut-list-revision-release", [
        ["Part identity and assembly", "Record stable part ID, description, room, cabinet, or assembly.", "W03-SIDE-L / wall cabinet 03"],
        ["Quantity and handedness", "Record total quantity and distinguish left, right, mirrored, or matched parts.", "Qty 2 / one left, one right"],
        ["Finished dimensions", "Record length, width, thickness, and which dimension follows grain.", "762 × 298 × 18 mm / grain length"],
        ["Edge and machining notes", "Record banding, grooves, dados, holes, show faces, and trim allowance.", "Band front; 6 mm back groove"],
      ]],
      ["plywood-sheet-requirement", "Plywood Sheet Requirement Worksheet", "Reconcile part area, complete layouts, usable sheet size, kerf, trim, defects, contingency, and whole-sheet purchasing.", "Document why the purchase quantity differs from an area-only minimum.", "plywood-order-release", [
        ["Material group and usable sheet", "Record grade, core, face, thickness, grain, and measured usable dimensions.", "Birch veneer core / 95.5 × 47.5 in"],
        ["Area-only minimum", "Record total finished-part area and mathematical minimum sheets.", "12,940 sq in / 3 sheets minimum"],
        ["Complete layout result", "Record optimizer, method version, sheet count, and rejected parts.", "CutList / 4 sheets / 0 rejected"],
        ["Purchase adjustment", "Record spare policy, defects, stock on hand, order quantity, and reason.", "Buy 5; one matched-face spare"],
      ]],
      ["lumber-board-foot-purchase", "Lumber Board-Foot Purchase Worksheet", "Convert finished solid-wood parts into rough dimensions, board feet, grade, length mix, milling loss, and purchase quantity.", "Preserve the assumptions between finished parts and the rough lumber order.", "lumber-order-release", [
        ["Finished-part demand", "Group parts by finished thickness, width, clear length, and quantity.", "Rails 3/4 × 2 × 28 in / qty 8"],
        ["Rough-size allowance", "Add thickness, width, end trim, defect, and matching allowances.", "Buy 4/4; +1 in width; +4 in length"],
        ["Board-foot basis", "Record calculated volume, yield factor, and adjusted board feet.", "18.4 bf / 65% yield / 28.3 bf"],
        ["Purchase specification", "Record species, grade, cut, moisture, length mix, and ordered volume.", "FAS maple / 8–10 ft / 32 bf"],
      ]],
      ["material-group-specification", "Material Group Specification Worksheet", "Define one stock group by product, actual thickness, face, core, finish, grain, usable size, substitution rules, and part membership.", "Prevent parts with different purchasing or machining requirements from being optimized as interchangeable stock.", "material-thickness-verification", [
        ["Material code and product", "Assign a unique code and full supplier-facing description.", "PB18-WH / 18 mm white prefinished birch"],
        ["Actual and usable size", "Record measured thickness plus accepted sheet or board dimensions.", "17.7 mm / 2440 × 1215 mm usable"],
        ["Appearance and orientation", "Record show face, grain, sequence, lot, and defect limits.", "A face outward / vertical grain"],
        ["Allowed substitution", "State who can approve alternatives and which properties cannot change.", "No core or finish substitution"],
      ]],
      ["kerf-trim-assumption", "Kerf & Trim Assumption Worksheet", "Record measured blade kerf, edge-trim loss, usable stock size, cleanup cuts, and sensitivity checks for a layout.", "Make material-loss assumptions visible and test whether the sheet count depends on optimistic inputs.", "saw-preflight", [
        ["Blade and measured kerf", "Record machine, blade, test material, cut method, and measured kerf.", "Track saw / 2.4 mm on test strip"],
        ["Edge-trim plan", "Record trim reserved on each edge and why it is needed.", "6 mm each edge for damage"],
        ["Usable stock dimensions", "Calculate the remaining length and width after accepted trim.", "2428 × 1203 mm"],
        ["Sensitivity result", "Record sheet count at baseline and a conservative kerf or trim case.", "4 sheets baseline; 5 at 12 mm trim"],
      ]],
      ["grain-face-sequence", "Grain, Face & Sequence Worksheet", "Assign show faces, grain direction, rotation permissions, matching groups, sequence numbers, and replacement strategy.", "Keep appearance-critical parts together while clearly identifying parts that may rotate for yield.", "grain-face-orientation-release", [
        ["Appearance group", "Group doors, fronts, ends, or panels that must match.", "Island fronts group G2"],
        ["Face and grain rule", "Record show face and required grain direction for every group.", "A face / vertical / no rotation"],
        ["Sequence and sheet map", "Record installed order and intended source-sheet positions.", "D1-D6 left to right / sheet 04"],
        ["Replacement rule", "State whether a spare must remain adjacent, matched, or separately finished.", "Keep one matched blank beside D6"],
      ]],
      ["hardware-purchase", "Hardware Purchase Worksheet", "Reconcile hardware models, quantities, packs, mounting accessories, handedness, finishes, spares, and lead times.", "Connect each hardware order line to the openings and parts it must fit.", "hardware-order-release", [
        ["Hardware model and use", "Record manufacturer, model, size, finish, and assigned openings.", "110° hinge H-71 / doors D1-D12"],
        ["Calculated quantity", "Record pieces per assembly, assembly count, and required total.", "2 per door × 12 = 24"],
        ["Pack and order quantity", "Record pack size, whole-pack rounding, spare policy, and ordered amount.", "10/box; order 3 boxes"],
        ["Accessories and constraints", "Record plates, screws, jigs, clips, clearances, and lead time.", "0 mm plate; 35 mm cup; 14 days"],
      ]],
      ["edge-banding-quantity", "Edge Banding Quantity Worksheet", "Calculate banded edge lengths by material, thickness, width, finish, oversize allowance, setup loss, and roll purchasing.", "Show how part-edge demand becomes a practical banding order with traceable waste.", "edge-banding-order", [
        ["Edge schedule", "Group parts by which edges receive banding and total each finished length.", "Shelf fronts: 18 × 762 mm"],
        ["Band specification", "Record material, thickness, width, color, finish, and adhesive system.", "1 mm ABS / 23 mm / white"],
        ["Process allowance", "Add end trim, setup, splice, defect, and test-piece allowances.", "10% plus 2 m setup"],
        ["Purchase conversion", "Record required length, roll size, stock on hand, and order quantity.", "38.4 m need / 50 m roll / order 1"],
      ]],
      ["offcut-inventory", "Sheet-Goods Offcut Inventory Worksheet", "Record reusable offcut dimensions, material, face, grain, condition, location, and reservation before purchasing new stock.", "Create a searchable stock record that credits only verified remnants against a project.", "offcut-inventory-release", [
        ["Offcut identity and location", "Assign an ID and exact rack, bin, or project location.", "BIR18-042 / rack A slot 6"],
        ["Material and condition", "Record product, thickness, faces, grain, damage, and moisture condition.", "Birch 18 mm / A-B / corner chip"],
        ["Measured usable rectangle", "Record the largest verified usable length and width, not the rough outline.", "812 × 476 mm usable"],
        ["Reservation and disposition", "Record intended part, project, expiry review, and retain/scrap decision.", "Reserved for shelf S4 until 2026-08-15"],
      ]],
      ["purchase-reconciliation", "Material Purchase Reconciliation Worksheet", "Bridge calculated requirement, usable stock, contingency, supplier units, ordered, received, accepted, returned, and back-ordered quantities.", "Explain every difference between the released material plan and the physical stock available for production.", "purchase-reconciliation", [
        ["Calculated requirement", "Record complete-layout or quantity basis for each material code.", "PB18-WH / 12 complete sheets"],
        ["Usable stock and contingency", "Record accepted inventory, retained offcuts, and approved reserve.", "2 sheets stock + 1 contingency"],
        ["Order and receipt", "Record ordered, shipped, received, accepted, held, and returned units.", "Order 11 / accept 10 / hold 1"],
        ["Variance and owner", "State shortage or surplus, reason, action, responsible person, and due date.", "Short 1 / damaged edge / buyer 7-28"],
      ]],
    ],
  }),
  makeCategory({
    slug: "machine-cutting-records",
    name: "Machine Setup & Cutting Records",
    description: "Record machines, tooling, references, test cuts, first articles, sampling results, and setup changes during production.",
    stage: "before and during cutting, routing, drilling, boring, or CNC production",
    baseFields: [
      ["Project, batch, and revision", "Identify the released project, material batch, and cut-list revision.", "Wardrobe / batch 02 / Rev D"],
      ["Operator and date", "Record who set up and ran the process plus the production date.", "J. Wu / 2026-07-26"],
      ["Machine and tooling", "Identify machine, blade, bit, cutter, jig, or program version.", "Table saw TS-2 / 80T blade"],
      ["Reference method", "State the face, edge, fence, stop, datum, or coordinate origin.", "Show face up / factory left edge"],
    ],
    links: [
      ["/checklists/first-article-cut-release/", "First-article cut release", "Checklist"],
      ["/learn/cut-dimension-drift-sampling-plan/", "Cut-dimension sampling plan", "Learn"],
      ["/kerf-calculator/", "Kerf calculator", "Calculator"],
    ],
    topics: [
      ["saw-setup-record", "Saw Setup Record Worksheet", "Document blade, fence or guide, kerf test, support, extraction, reference face, first cut, and setup approval.", "Create a repeatable saw setup record before a batch of project parts is exposed to it.", "saw-preflight", [
        ["Blade and condition", "Record blade model, tooth count, sharpness, installation, and guard setup.", "250 mm / 80T / sharpened 7-20"],
        ["Fence or guide verification", "Record parallel, square, track, stop, and scale checks.", "Fence within 0.1 mm over 600"],
        ["Kerf and sample cut", "Record measured kerf, sample material, target, and actual dimension.", "Kerf 2.6 mm / target 300 / actual 300.1"],
        ["Support and extraction", "Record infeed, outfeed, sheet support, dust control, and helper plan.", "Outfeed clear / extractor gate TS"],
      ]],
      ["first-article-inspection", "First-Article Cut Inspection Worksheet", "Inspect the first completed part for dimensions, square, edge quality, grain, face, machining, label, and assembly fit.", "Release the batch only after one representative part proves the setup and part definition agree.", "first-article-cut-release", [
        ["Part and target", "Record part ID, target dimensions, tolerance, material, and orientation.", "SIDE-L / 720 × 560 / ±0.5 mm"],
        ["Measured result", "Record actual length, width, thickness, diagonals, and critical features.", "720.1 × 559.8 / diagonals equal"],
        ["Quality and identity", "Inspect edges, faces, grain, damage, label, and handedness.", "Pass / A face out / left confirmed"],
        ["Fit and release", "Record mock assembly, hardware test, disposition, approver, and time.", "Fits groove / released 10:42"],
      ]],
      ["batch-rip-log", "Batch Rip-Cut Log Worksheet", "Track rip width, reference edge, fence setting, first and interval samples, quantity, drift, and affected parts.", "Detect a moving fence or changing reference before an entire repeated-rip batch is complete.", "batch-rip-release", [
        ["Rip group and quantity", "Record part IDs, target width, stock, and planned quantity.", "Shelves S1-S18 / 298 mm / qty 18"],
        ["Initial setting and sample", "Record fence value, test result, and first accepted part.", "Fence 298.2 / first 298.0"],
        ["Interval readings", "Record sample sequence, time, actual width, and trend.", "#6 298.0; #12 297.7"],
        ["Adjustment and containment", "Record stop point, correction, suspect range, recheck, and disposition.", "Hold #7-12 / clean fence / remeasure"],
      ]],
      ["crosscut-stop-log", "Crosscut Stop Setup Worksheet", "Record stop position, reference end, saw geometry, sample length, repeated checks, stock buildup, and reset events.", "Keep repeated crosscuts traceable when stops, debris, or end references can change finished length.", "crosscut-release", [
        ["Crosscut group", "Record part IDs, target length, end treatment, and quantity.", "Rails R1-R24 / 552 mm / qty 24"],
        ["Stop and reference", "Record stop type, scale value, reference end, and blade side.", "Flip stop / finished left end"],
        ["Sample sequence", "Record first, interval, and final actual lengths.", "552.0 / 552.1 / 552.0"],
        ["Reset events", "Record cleanup, stop movement, blade change, interruption, and new first article.", "Debris cleared at part 12; reapproved"],
      ]],
      ["track-saw-breakdown", "Track-Saw Sheet Breakdown Worksheet", "Plan sheet support, reference corner, rough-cut sequence, track offsets, oversize allowance, labels, and retained offcuts.", "Connect a safe sheet breakdown sequence to the final-reference operations that follow.", "track-saw-sheet-breakdown", [
        ["Sheet identity and orientation", "Record material code, sheet ID, show face, grain, and reference corner.", "PB18-07 / A face down / NE origin"],
        ["Breakdown sequence", "List rough cuts in order with target rough sizes and track offset.", "Cut 1 at 610 mm; retain factory left"],
        ["Support and cut path", "Record foam or table support, cable path, blade depth, and no-cut zones.", "25 mm foam / depth 21 mm"],
        ["Labels and offcuts", "Record resulting panel IDs, reference edges, and reusable remnants.", "Blank B3 / reference long edge / offcut O7"],
      ]],
      ["router-setup-record", "Router Setup Record Worksheet", "Document bit, speed, depth, fence, reference face, passes, climb-cut restrictions, test piece, and inspection.", "Preserve the settings and approved sample for a repeat routing operation.", "router-operation-release", [
        ["Bit and speed", "Record cutter model, diameter, condition, collet engagement, and speed.", "12 mm spiral / 18,000 rpm"],
        ["Depth and fence", "Record target depth, pass schedule, fence or template offset, and reference face.", "6 mm total / two 3 mm passes"],
        ["Test piece result", "Record sample material, actual width/depth, edge quality, and fit.", "Groove 12.1 × 6.0 / back fits"],
        ["Production checks", "Record interval, chip clearing, bearing or guide condition, and final sample.", "Check every 10 parts"],
      ]],
      ["drilling-boring-record", "Drilling & Boring Setup Worksheet", "Record hole pattern, datum, jig or machine, bit, depth, spacing, handedness, test panel, and interval verification.", "Prevent a repeated hole pattern from being mirrored, shifted, or drilled through a show face.", "drilling-boring-release", [
        ["Pattern and datum", "Record hole IDs, coordinates or spacing, origin, face, and handedness.", "Shelf pins / 32 mm / front-bottom origin"],
        ["Bit and depth control", "Record diameter, point style, stop setting, backer, and breakthrough rule.", "5 mm brad point / 12 mm deep"],
        ["Test pattern", "Record test panel, first and last hole positions, depth, and hardware fit.", "Panel T1 / fit pass"],
        ["Batch verification", "Record interval panel, jig cleaning, stop changes, and suspect parts.", "Verify first of each cabinet side pair"],
      ]],
      ["dado-rabbet-groove-record", "Dado, Rabbet & Groove Setup Worksheet", "Capture cutter width, target depth, reference face, offsets, test-fit part, pass sequence, and production measurements.", "Make joinery geometry repeatable and tied to the actual mating material thickness.", "dado-rabbet-groove-release", [
        ["Mating material", "Record actual thickness, part ID, fit class, and finish allowance.", "Back panel 5.8 mm / slip fit"],
        ["Cutter and target geometry", "Record cutter, target width, depth, shoulder, and offset.", "6 mm bit / 6.1 × 8 mm groove"],
        ["Reference and sequence", "Record face, edge, fence side, pass count, and order relative to sizing.", "Inside face down / groove before crosscut"],
        ["Test and production result", "Record measured joint, sample fit, first part, and interval checks.", "6.15 × 8.0 / pass"],
      ]],
      ["cnc-job-record", "CNC Job Record Worksheet", "Record file revision, postprocessor, tool list, stock origin, workholding, zero, simulation, test cut, and completed parts.", "Tie physical CNC output to one approved file and setup while preserving rejected or rerun parts.", "cnc-job-release", [
        ["Program identity", "Record file name, checksum or version, postprocessor, and approved drawing.", "CAB_R3_v12.nc / Rev D"],
        ["Stock and workholding", "Record stock size, face, origin, spoilboard, clamps, vacuum zones, and keep-outs.", "2440 × 1220 / lower-left zero"],
        ["Tools and simulation", "Record tool numbers, measured diameters, stickout, paths reviewed, and collision result.", "T3 6 mm compression / simulation pass"],
        ["Run and reconciliation", "Record start/end, completed, held, rejected, rerun parts, and remaining stock.", "42 complete / 1 held / rerun P17"],
      ]],
      ["cut-dimension-sampling", "Cut-Dimension Sampling Worksheet", "Define critical dimensions, sampling frequency, actual readings, stop limits, containment windows, causes, and restart evidence.", "Detect production drift and identify exactly which parts require reinspection after a failed sample.", "first-article-cut-release", [
        ["Critical dimension and limit", "Record feature, target, tolerance, and measurement method.", "Drawer width 558.0 ±0.4 mm"],
        ["Sampling plan", "Record first, interval, trigger-based, and final sample rules.", "First 2, every 8, after any stop change"],
        ["Observed readings", "Record part ID, time, actual value, and pass or fail.", "D16 / 14:20 / 557.5 / fail"],
        ["Containment and restart", "Record last good sample, suspect range, cause, correction, and new approval.", "Hold D9-D16 / reset stop / D17 pass"],
      ]],
    ],
  }),
  makeCategory({
    slug: "assembly-hardware-records",
    name: "Assembly & Hardware Records",
    description: "Document dry fits, joinery, glue-ups, cabinet geometry, hardware models, settings, adjustments, and accepted assemblies.",
    stage: "during dry fit, assembly, hardware installation, and functional adjustment",
    baseFields: [
      ["Project, assembly, and revision", "Identify room, cabinet, assembly ID, and released revision.", "Kitchen / B07 / Rev C"],
      ["Assembler and date", "Record the person responsible and assembly date or shift.", "S. Patel / 2026-07-26"],
      ["Material and part IDs", "List the parts and material group entering the operation.", "Sides S-L/S-R; bottom B1; PB18"],
      ["Reference and acceptance rule", "State the face, edge, datum, drawing note, or tolerance used.", "Front edges flush / diagonals within 1 mm"],
    ],
    links: [
      ["/checklists/dry-fit-release/", "Dry-fit release", "Checklist"],
      ["/learn/cabinet-box-squareness-before-cutting/", "Cabinet squareness workflow", "Learn"],
      ["/cut-list-calculator/", "Cut list calculator", "Calculator"],
    ],
    topics: [
      ["dry-fit-record", "Dry-Fit Assembly Worksheet", "Record part identity, joint fit, sequence, clamps, diagonals, gaps, hardware clearance, and corrections before adhesive or final fasteners.", "Prove that the complete assembly closes, squares, and functions before the operation becomes irreversible.", "dry-fit-release", [
        ["Parts and joints present", "Reconcile every required part, joint, handed component, and temporary spacer.", "8 parts / all IDs confirmed"],
        ["Fit observations", "Record gap, flushness, insertion force, rocking, bow, and interference by joint.", "J3 gap 0.4 mm at rear"],
        ["Geometry and function", "Record diagonals, twist, opening sizes, moving clearance, and hardware trial.", "D1 1024 / D2 1024.5 mm"],
        ["Corrections and release", "Record rework, changed parts, new revision, approver, and release status.", "Ease J3 shoulder / recheck passed"],
      ]],
      ["glue-up-record", "Glue-Up Record Worksheet", "Capture adhesive, batch, environment, open time, clamp sequence, pressure, diagonals, squeeze-out, cure, and release.", "Preserve enough process evidence to explain the accepted glue-up and any later joint issue.", "glue-up-release", [
        ["Adhesive and environment", "Record product, lot, temperature, humidity, and substrate condition.", "PVA-X lot 441 / 23°C / 48% RH"],
        ["Timing", "Record mix or application start, assembly, clamp, cleanup, and unclamp times.", "Apply 09:12 / clamped 09:19"],
        ["Clamp and geometry", "Record clamp positions, cauls, pressure observations, and diagonal readings.", "6 clamps / D1-D2 difference 0.5 mm"],
        ["Cure and release", "Record required cure, actual release time, inspection, and disposition.", "Released after 8 h / pass"],
      ]],
      ["cabinet-box-square-record", "Cabinet Box Squareness Worksheet", "Record side, top, bottom, back, diagonal, opening, twist, and reference-plane measurements during cabinet assembly.", "Keep cabinet geometry available for doors, drawers, installation, and any correction decision.", "cabinet-box-squaring", [
        ["Outside dimensions", "Record finished width, height, depth, and key opening sizes.", "W 762.1 / H 876.0 / D 584.2 mm"],
        ["Diagonal readings", "Record both front and back diagonals before final fastening.", "Front 1161.2 / 1161.6 mm"],
        ["Twist and reference planes", "Check front edges, back plane, shelf references, and rocking.", "Front flush / rear-left high 0.6 mm"],
        ["Back and correction", "Record back fit, fastener sequence, correction applied, and final result.", "Back squared box / final diff 0.3 mm"],
      ]],
      ["drawer-box-assembly-record", "Drawer Box Assembly Worksheet", "Track drawer part dimensions, groove fit, diagonal, bottom, slide clearance, fasteners, labels, and final movement.", "Connect the assembled drawer geometry to its specific opening and slide system.", "drawer-box-assembly", [
        ["Drawer and opening identity", "Record drawer ID, cabinet opening, slide model, and target clearance.", "D04 / B07 upper / UM-21"],
        ["Parts and groove fit", "Record side, front, back, bottom IDs and actual bottom/groove fit.", "Bottom 6.0 mm / groove 6.2 mm"],
        ["Assembly geometry", "Record width, length, diagonals, twist, and fastener or joint result.", "Width 533.8 / diagonals within 0.4"],
        ["Slide and movement test", "Record installed clearance, travel, latch, load test, and adjustment.", "12.7 mm each side / full travel pass"],
      ]],
      ["face-frame-assembly-record", "Face Frame Assembly Worksheet", "Document rail and stile IDs, finished widths, joint method, reference face, diagonals, opening sizes, flushness, and cabinet fit.", "Preserve the relationship between face-frame openings and the boxes, doors, and drawers they control.", "face-frame-assembly", [
        ["Member identity and orientation", "Record rails, stiles, finished widths, show face, and grain selection.", "L stile FS1 / 38.0 mm"],
        ["Joint setup and result", "Record joinery, fastener, glue, clamp, and face-flush observation.", "Pocket screws / faces within 0.2 mm"],
        ["Frame geometry", "Record overall dimensions, diagonals, and every controlled opening.", "Door opening 418 × 702 mm"],
        ["Box fit and overhang", "Record alignment, reveal, projection, scribe, and attachment result.", "12 mm left overhang / pass"],
      ]],
      ["pocket-hole-assembly-record", "Pocket-Hole Assembly Worksheet", "Record stock thickness, jig setting, bit stop, screw, hole face, clamp, test joint, and finished alignment.", "Keep pocket-hole settings and breakthrough checks tied to the actual material batch.", "pocket-hole-assembly", [
        ["Measured stock and settings", "Record actual thickness, jig scale, drill stop, and bit condition.", "18.1 mm / jig 18 / stop 42 mm"],
        ["Screw and hole pattern", "Record screw type, length, quantity, spacing, and permitted face.", "32 mm coarse / 3 holes / hidden face"],
        ["Test joint", "Record pull-up, breakthrough, split, alignment, and torque method.", "No breakthrough / flush within 0.3 mm"],
        ["Production result", "Record assembly IDs, rejected holes, repairs, and final inspection.", "Frames F1-F6 / one plugged and redrilled"],
      ]],
      ["dowel-loose-tenon-record", "Dowel & Loose-Tenon Worksheet", "Track reference faces, cutter or jig settings, spacing, depth, tenon size, test fit, glue space, and joint alignment.", "Make paired mortises or dowel holes repeatable across matched parts and assembly stages.", "dowel-domino-joinery", [
        ["Joint and reference marks", "Record mating part IDs, face, edge, centerline, and joint number.", "J12 / A faces out / top reference"],
        ["Tool settings", "Record cutter or drill size, depth, width, offset, spacing, and machine mode.", "8 mm / 24 mm deep / tight mode"],
        ["Dry test", "Record insertion, bottoming, lateral play, face alignment, and square.", "Closes fully / 0.2 mm face step"],
        ["Production and correction", "Record completed joints, miscuts, repairs, and approved disposition.", "20 joints / J18 remade"],
      ]],
      ["hinge-installation-record", "Concealed Hinge Installation Worksheet", "Record hinge and plate models, cup drilling, setbacks, door and cabinet dimensions, screw settings, overlays, and final function.", "Tie each door's drilling and adjustment to the exact hinge system and opening.", "concealed-hinge-release", [
        ["Door, opening, and hardware", "Record IDs, hinge model, plate, door thickness, and opening geometry.", "D7 / H71 + P0 / 19 mm"],
        ["Cup and plate drilling", "Record cup diameter, depth, edge setback, vertical locations, and pilot sizes.", "35 × 12.5 mm / setback 4 mm"],
        ["Initial overlay and reveal", "Record target and actual overlay, paired gap, top, and bottom reveals.", "Overlay 18.0 / gap 2.2 mm"],
        ["Adjustment and function", "Record screw adjustments, opening angle, collision, soft close, and final signoff.", "Depth +0.5 turn / function pass"],
      ]],
      ["drawer-slide-installation-record", "Drawer Slide Installation Worksheet", "Capture slide model, opening, drawer size, setback, height, parallel, screw positions, clearances, and loaded function.", "Preserve the dimensional and adjustment record for each drawer-slide pair.", "drawer-slide-release", [
        ["Slide and drawer identity", "Record cabinet, drawer, slide model, length, rating, and handed parts.", "B07-D4 / UM-21 / 500 mm"],
        ["Opening and drawer sizes", "Record actual opening, drawer width, required clearance, and variance.", "Opening 560.0 / drawer 533.8 mm"],
        ["Mounting geometry", "Record setback, height, parallel, level, and screw or clip positions.", "Setback 3 mm / rails within 0.4"],
        ["Loaded function", "Record latch, travel, soft close, front adjustment, load, and release.", "20 kg test / full close pass"],
      ]],
      ["reveal-adjustment-record", "Door & Drawer Reveal Adjustment Worksheet", "Record opening IDs, target gaps, initial readings, hinge or slide adjustments, front positions, collisions, and final reveals.", "Create a final alignment record that distinguishes hardware adjustment from resized or remade fronts.", "door-overlay-reveal", [
        ["Target reveal standard", "Record top, bottom, side, paired, and between-front target gaps.", "2.0 mm perimeter / 3.0 mm pair"],
        ["Initial readings", "Measure gaps at multiple points and note proud, inset, twist, or collision.", "Left 1.2–2.6 mm / upper proud"],
        ["Adjustment actions", "Record hinge, plate, slide, clip, spacer, or front movement by ID.", "H2 lateral +0.8 mm"],
        ["Final readings and disposition", "Record final gaps, function, remaining exception, and approver.", "1.9–2.2 mm / accepted"],
      ]],
    ],
  }),
  makeCategory({
    slug: "installation-field-change-records",
    name: "Installation & Field Change Records",
    description: "Connect shop output to real rooms, structure, services, leveling, scribing, anchoring, changes, punch work, and acceptance.",
    stage: "during delivery, installation, field modification, and room-by-room acceptance",
    baseFields: [
      ["Project, room, and assembly", "Identify site, room, elevation, cabinet, or installed component.", "Residence A / kitchen / wall run W"],
      ["Drawing revision and install date", "Record the released documents and when the condition was installed or checked.", "Rev F / 2026-07-26"],
      ["Installer and verifier", "Identify the installer and independent verifier or responsible trade.", "Install JP / verify ML"],
      ["Site datum and reference", "State the floor, wall, centerline, finished face, or benchmark used.", "Laser line 2134 mm above FFL"],
    ],
    links: [
      ["/checklists/final-installation-release/", "Final installation release", "Checklist"],
      ["/learn/room-by-room-installation-handoff/", "Room-by-room installation handoff", "Learn"],
      ["/apps/cutlist/", "CutList project records", "App"],
    ],
    topics: [
      ["delivery-load-in-record", "Delivery & Load-In Worksheet", "Record package IDs, condition, room allocation, access route, protection, missing items, damage, and custody transfer.", "Reconcile what reached the site before components are unpacked, mixed, or installed.", "delivery-load-in-release", [
        ["Package and room allocation", "Record package IDs, cabinet or part IDs, room, and planned sequence.", "PKG-12 / W03-W05 / kitchen"],
        ["Arrival condition", "Record wrap, edge, face, moisture, hardware, and photo evidence.", "Corner dent on W04 / photo 118"],
        ["Access and protection", "Record route, floor or wall protection, lifting method, and staging location.", "South entry / ram board / two-person"],
        ["Reconciliation", "Record received, missing, damaged, held, accepted, and responsible action.", "W04 held / replacement front due 7-29"],
      ]],
      ["wall-cabinet-installation-record", "Wall Cabinet Installation Worksheet", "Track layout lines, structure, fasteners, ledger, cabinet sequence, level, plumb, face alignment, and final anchoring.", "Preserve the installed position and attachment evidence for a wall-cabinet run.", "wall-cabinet-installation", [
        ["Layout and structure", "Record top/bottom lines, stud or blocking locations, and verified service zones.", "Top 2134 mm / studs at 406 mm"],
        ["Fastener specification", "Record type, size, quantity, location, washer or rail, and approved substrate.", "6 × 80 mm structural screws"],
        ["Position and alignment", "Record level, plumb, face plane, cabinet joints, and crown or ceiling allowance.", "Run level within 1 mm over 3 m"],
        ["Final attachment and load path", "Record all anchors, connection photos, exceptions, and verifier.", "Photo set WC-08 / pass"],
      ]],
      ["base-cabinet-installation-record", "Base Cabinet Installation Worksheet", "Record floor high point, reference line, shims, cabinet order, level, face plane, appliance openings, fillers, and anchoring.", "Connect base cabinet installation geometry to countertops, appliances, drawers, and wall conditions.", "base-cabinet-installation", [
        ["Floor profile and reference", "Record high point, total variation, cabinet-top line, and finished floor status.", "High at B03 / 9 mm variation"],
        ["Shim and level record", "Record shim locations, thicknesses, support under dividers, and level readings.", "B05 rear-right 6 mm shim"],
        ["Openings and face plane", "Record appliance widths, cabinet joints, face alignment, and countertop support.", "Range opening 762.5 mm"],
        ["Anchoring and final function", "Record wall/floor attachment, door/drawer tests, and exceptions.", "All drawers pass / B02 side held"],
      ]],
      ["filler-scribe-installation-record", "Filler & Scribe Installation Worksheet", "Document measured profile, blank size, face alignment, door clearance, trim method, final reveal, attachment, and finish condition.", "Make site-fitted fillers traceable without losing cabinet width or hardware clearance.", "filler-scribe-installation", [
        ["Field gap profile", "Measure gap at multiple heights or depths and identify maximum variation.", "12 / 18 / 24 / 21 mm"],
        ["Blank and target reveal", "Record blank width, grain, face alignment, door/pull clearance, and final reveal.", "Blank 38 mm / target reveal 3 mm"],
        ["Scribe and trim method", "Record transfer tool, offset, cut sequence, edge finish, and trial fits.", "Compass 3 mm / jigsaw then plane"],
        ["Final fit and attachment", "Record residual gaps, fasteners or adhesive, touch-up, and approval.", "Gap under 1 mm / accepted"],
      ]],
      ["tall-cabinet-installation-record", "Tall Cabinet Installation Worksheet", "Track ceiling and floor limits, tipping path, fillers, plumb, anchoring, anti-tip provisions, service clearances, and door function.", "Preserve how a tall cabinet was safely positioned, adjusted, and restrained in the real opening.", "tall-cabinet-installation", [
        ["Envelope and tipping path", "Record cabinet dimensions, ceiling, diagonal/tip requirement, and assembly plan.", "Cab 2380 high / ceiling 2440"],
        ["Level, plumb, and fillers", "Record shim points, wall lean, side/top fillers, and face alignment.", "Top right shim 4 mm"],
        ["Anchoring and restraint", "Record structure, bracket or rail, fasteners, anti-tip method, and photos.", "Two rail points into blocking"],
        ["Services and function", "Record appliance, vent, outlet, access, door swing, and final test.", "Oven vent clearance pass"],
      ]],
      ["floating-shelf-installation-record", "Floating Shelf Installation Worksheet", "Record shelf and bracket models, wall structure, anchor locations, drilling, level, embedment, load limits, and final movement.", "Tie the installed shelf to verified structure and the current bracket instructions.", "floating-shelf-installation", [
        ["Shelf and bracket identity", "Record dimensions, material, bracket model, rating source, and finish.", "Shelf S2 / bracket FB-400"],
        ["Structure and locations", "Record studs, blocking, masonry, services, bracket spacing, and edge distances.", "Studs at 406 mm / two brackets"],
        ["Fasteners and drilling", "Record fastener type, diameter, length, pilot, embedment, and torque method.", "8 × 75 mm / 55 mm embedment"],
        ["Final geometry and load boundary", "Record level, wall gap, movement, test load, and posted limit.", "Level within 0.5 mm / no movement"],
      ]],
      ["built-in-bookcase-installation-record", "Built-In Bookcase Installation Worksheet", "Track wall survey, leveling base, modules, joints, scribes, anchoring, shelves, trim, and room acceptance.", "Connect shop modules into one level, anchored, scribed installation with traceable field adjustments.", "built-in-bookcase-installation", [
        ["Opening and base", "Record final envelope, floor high point, platform or toe-kick level, and wall variation.", "Opening 3210 mm / base level ±0.5"],
        ["Module sequence and joints", "Record module IDs, order, clamps, joining fasteners, and face alignment.", "M1-M4 left to right"],
        ["Scribes, trim, and interfaces", "Record fillers, crown, baseboard, outlets, walls, ceiling, and finish touch-up.", "Left scribe 8–17 mm"],
        ["Anchoring and final check", "Record structure, anchors, shelf fit, reveal, photos, and acceptance.", "Anchors at each module / pass"],
      ]],
      ["closet-system-installation-record", "Closet System Installation Worksheet", "Record wall dimensions, rail or cleat level, studs, module positions, shelf and rod heights, drawers, clearances, and anchors.", "Preserve the installed closet layout and every site-driven adjustment for future changes.", "closet-system-installation", [
        ["Final wall and obstruction map", "Record width, height, depth, baseboard, outlets, doors, and access panels.", "Rear wall 2786 mm / outlet at 620"],
        ["Rail, cleat, and structure", "Record datum height, stud locations, fasteners, level, and end conditions.", "Rail at 2040 mm / five studs"],
        ["Module and component positions", "Record tower, shelf, rod, drawer, and hamper coordinates.", "Tower T2 starts 1450 mm"],
        ["Function and capacity checks", "Record door clearance, drawer travel, shelf support, rod bracket, and final load boundary.", "Drawer clears casing 18 mm"],
      ]],
      ["field-change-record", "Field Change Record Worksheet", "Document the observed condition, affected parts, old and proposed values, cause, options, approval, revision, and disposition.", "Stop informal site changes from separating the installed work from drawings, cut lists, purchases, and retained records.", "final-installation-release", [
        ["Observed condition", "Record location, date, measurement, photo, and why released work cannot proceed unchanged.", "Wall 14 mm narrower / photo FC-22"],
        ["Impact assessment", "List affected parts, hardware, finishes, orders, schedule, cost, and completed work.", "F1/F2, crown, install +2 h"],
        ["Decision and approval", "Record options, selected solution, approver, constraints, and time.", "Reduce fillers equally / approved 11:05"],
        ["Revision and disposition", "Record updated drawing/list, superseded items, rework/remake, labels, and notification.", "Rev G issued / F1-F2 recut"],
      ]],
      ["final-installation-record", "Final Installation Acceptance Worksheet", "Record completed scope, dimensions, level, plumb, reveals, function, anchors, utilities, protection, punch items, and acceptance.", "Create a room-level installation record before tools, packaging, and access disappear.", "final-installation-release", [
        ["Scope reconciliation", "List installed, missing, held, transferred, and owner-supplied items.", "All cabinets; two fronts held"],
        ["Geometry and appearance", "Record level, plumb, alignment, reveals, scribe gaps, finish, and damage.", "Run level / reveals 2.0–2.4 mm"],
        ["Function and attachment", "Test doors, drawers, hardware, appliances, anchors, and access.", "18 doors / 12 drawers pass"],
        ["Punch and acceptance", "Record open items, owner, due date, photos, room protection, and signer.", "P3 touch-up / due 7-28"],
      ]],
    ],
  }),
  makeCategory({
    slug: "finish-handoff-closeout",
    name: "Finish, Handoff & Closeout",
    description: "Record surface preparation, approved samples, coating conditions, cure, defects, punch work, delivered documents, and final project variance.",
    stage: "during finishing, inspection, client handoff, punch work, and project closeout",
    baseFields: [
      ["Project, area, and revision", "Identify the project, room, assembly, finish schedule, and active revision.", "Library / south wall / Finish Rev 4"],
      ["Responsible person and date", "Record applicator, inspector, or handoff owner plus the relevant date.", "R. Kim / 2026-07-26"],
      ["Material or finish system", "Identify substrate, product, color, sheen, lot, and current instructions.", "Birch / ClearCoat 20 / satin / lot 81"],
      ["Acceptance source", "Record approved sample, specification, manufacturer sheet, drawing, or signed standard.", "Sample S-04 approved 2026-07-18"],
    ],
    links: [
      ["/checklists/project-closeout/", "Project closeout", "Checklist"],
      ["/learn/cut-list-yield-variance-closeout/", "Yield-variance closeout", "Learn"],
      ["/wood-waste-calculator/", "Wood waste calculator", "Calculator"],
    ],
    topics: [
      ["surface-preparation-record", "Surface Preparation Worksheet", "Record substrate condition, moisture, sanding sequence, dust removal, filler, edge treatment, masking, defects, and release.", "Prove the surface matches the approved finish system before the first irreversible coat.", "surface-preparation-release", [
        ["Substrate and moisture condition", "Record species or product, repairs, moisture reading, acclimation, and contamination.", "Birch veneer / 8% / no silicone"],
        ["Sanding and edge sequence", "Record abrasives, final grit, hand or machine method, and veneer protection.", "120-150-180 / hand edges"],
        ["Defects and repairs", "Record dents, glue, gaps, filler, burn-through, raised grain, and disposition.", "Two filled pins / sample accepted"],
        ["Cleaning and release", "Record vacuum, tack method, lighting, masking, inspector, and release time.", "Vacuum + approved wipe / 14:30"],
      ]],
      ["stain-sample-record", "Stain Sample Approval Worksheet", "Track substrate batch, preparation, conditioner, stain, application, dwell, wipe, topcoat, lighting, color notes, and approval.", "Preserve a repeatable sample system instead of relying on a color name or phone photo.", "stain-sample-approval", [
        ["Sample identity", "Record substrate offcut, face, grain, preparation, and sample number.", "Birch A face / 180 grit / S-04"],
        ["Product and application", "Record stain, lot, mix, conditioner, tool, dwell, wipe, and coats.", "Walnut 2:1 / 4 min dwell"],
        ["Topcoat and viewing", "Record sealer/topcoat, sheen, cure, lighting, orientation, and comparison time.", "Satin clear / daylight + warm LED"],
        ["Decision and limits", "Record approved, rejected, adjustment, approver, date, and allowed variation.", "Approved / match within adjacent panels"],
      ]],
      ["paint-finish-record", "Paint Finish Application Worksheet", "Record substrate, primer, paint, batch, thinning, equipment, environment, coats, film observations, cure, and inspection.", "Connect the accepted painted surface to a specific product system and application window.", "paint-finish-release", [
        ["Primer and preparation", "Record primer, dry time, sanding, repairs, and surface release.", "Bond primer / sand 220 after 6 h"],
        ["Paint and equipment", "Record product, color, sheen, lot, reduction, tip or roller, and pressure.", "Enamel white / satin / 1.8 mm tip"],
        ["Environment and coat times", "Record temperature, humidity, ventilation, start, recoat, and coat count.", "22°C / 52% / coats 09:00, 15:30"],
        ["Inspection and cure", "Record coverage, texture, runs, dust, blocking, hardness, touch-up, and release.", "Minor nibs sanded / release after 72 h"],
      ]],
      ["clear-coat-record", "Clear-Coat Application Worksheet", "Document sealer, clear finish, sheen, lot, mix, equipment, environment, coat schedule, sanding, cure, and defects.", "Keep every coat tied to the approved sample and product recoat window.", "clear-coat-release", [
        ["System and mix", "Record sealer, topcoat, catalyst, ratio, induction, pot life, and batch.", "2K clear / 10:1 / pot life 2 h"],
        ["Application setup", "Record spray or brush method, tip, pressure, wet film target, and test panel.", "1.3 mm / 1.8 bar / sample pass"],
        ["Coat schedule", "Record each coat time, sanding grit, cleaning, and recoat interval.", "Coat 1 08:40 / sand 320"],
        ["Cure and final surface", "Record cure condition, sheen, clarity, defects, repair, and handling release.", "Satin even / one dust nib repaired"],
      ]],
      ["edge-finish-record", "Plywood Edge Finish Worksheet", "Record edge type, core condition, banding or lipping, filler, sanding, primer, coating, samples, defects, and final acceptance.", "Match each plywood edge treatment to its visible use and downstream finish.", "plywood-edge-finish", [
        ["Edge identity and exposure", "Record part IDs, edge names, visible zone, core type, and required appearance.", "Shelves S1-S8 / front edges visible"],
        ["Treatment system", "Record banding, solid lipping, filler, veneer, radius, chamfer, or paint preparation.", "1 mm ABS / trim flush"],
        ["Process observations", "Record adhesion, seams, chips, voids, sanding, glue, and repair.", "No lift / one core void filled"],
        ["Finish and acceptance", "Record color, sheen, edge-face transition, sample, inspector, and result.", "Matches face within approved sample"],
      ]],
      ["between-coat-inspection-record", "Between-Coat Inspection Worksheet", "Inspect dryness, adhesion, sanding, dust, defects, coverage, film damage, recoat window, and corrective action between finish coats.", "Stop defects from being buried under the next coat and preserve the decision to continue.", "between-coat-inspection", [
        ["Coat identity and elapsed time", "Record product, coat number, application time, environment, and inspection time.", "Clear coat 2 / 16 h elapsed"],
        ["Surface condition", "Record dry state, adhesion, dust, nibs, runs, orange peel, pinholes, and coverage.", "Dry / three nibs / no runs"],
        ["Preparation for next coat", "Record sanding grit, scuff completeness, cleaning, repair, and masked areas.", "320 grit / vacuum + approved wipe"],
        ["Recoat release", "Record current recoat window, exception, inspector, and release or hold.", "Within 24 h / released 10:20"],
      ]],
      ["finish-cure-record", "Finish Cure & Handling Worksheet", "Track finish system, coat completion, cure conditions, hardness checks, stacking, wrapping, installation, cleaning, and use restrictions.", "Prevent a dry-to-touch surface from being packed, installed, or loaded before adequate cure.", "finish-cure-release", [
        ["Finish completion", "Record last coat, time, film condition, and manufacturer cure guidance.", "Last coat 7-24 16:00 / 7 days full cure"],
        ["Cure environment", "Record temperature, humidity, airflow, sunlight, and storage orientation.", "23°C / 48% / rack stored"],
        ["Handling milestones", "Record touch, sand, stack, wrap, transport, install, and service release times.", "Wrap after 72 h with breathable layer"],
        ["Restrictions and handoff", "Record cleaners, mats, heat, water, hardware, and client use limits.", "No wet cleaning for 7 days"],
      ]],
      ["punch-list-record", "Shop & Installation Punch List Worksheet", "Record location, observable issue, reference, owner, priority, correction, due date, evidence, verification, and disposition.", "Turn vague finish comments into owned, verifiable closeout items without erasing history.", "shop-punch-list", [
        ["Item and location", "Assign item ID and exact room, cabinet, part, face, or coordinate.", "P-017 / kitchen B04 left door"],
        ["Observed condition and standard", "Describe the issue and cite drawing, sample, function, or acceptance rule.", "Top reveal 4.2 mm vs 2 mm standard"],
        ["Owner and correction", "Record responsible person, repair or remake plan, access, and due date.", "Installer / adjust hinges / 7-28"],
        ["Verification and closure", "Record actual result, photo, verifier, date, and closed/waived/transferred status.", "2.1 mm / photo 411 / closed"],
      ]],
      ["client-handoff-record", "Client Handoff Worksheet", "Reconcile installed scope, operation, care, warranties, spare materials, keys, manuals, photos, signatures, open items, and contacts.", "Create a complete handoff package without treating unresolved punch work as silently accepted.", "client-handoff", [
        ["Scope and function review", "Record rooms reviewed, doors, drawers, hardware, appliances, and demonstrations.", "Kitchen and pantry / all functions shown"],
        ["Documents and materials", "Record manuals, warranties, finish care, touch-up, attic stock, keys, and digital files.", "Care sheet C2 / 3 spare shelves"],
        ["Open items and responsibilities", "List punch, exclusions, owner-supplied work, dates, contacts, and access.", "P-021 due 7-29 / installer owns"],
        ["Acceptance evidence", "Record photos, recipient, signatures, date, and any written reservations.", "Report HR-08 / signed with P-021 open"],
      ]],
      ["project-closeout-record", "Woodworking Project Closeout Worksheet", "Compare released scope, completed parts, purchased and used material, remakes, offcuts, revisions, costs, files, lessons, and final disposition.", "Preserve a usable as-built and variance record for the next estimate, layout, purchase, and project review.", "project-closeout", [
        ["Scope and revision close", "Record final installed scope, as-built revision, omitted or transferred items, and archive location.", "As-built Rev H / archive JOB-204"],
        ["Material and yield result", "Record ordered, used, returned, retained offcuts, scrap, remakes, and comparable yield basis.", "14 sheets ordered / 12.5 used"],
        ["Time, cost, and cause variance", "Record planned and actual values plus named causes for meaningful differences.", "+6 labor h / field wall change"],
        ["Lessons and ownership", "Record one supported process update, owner, due date, and documents or templates affected.", "Add final wall check / PM / template v3"],
      ]],
    ],
  }),
];

export const worksheetEntries = worksheetCategories.flatMap((category) =>
  category.topics.map((topic) => ({
    ...topic,
    category: category.name,
    categorySlug: category.slug,
    categoryDescription: category.description,
    stage: category.stage,
    links: category.links,
    baseFields: category.baseFields,
    fields: [...category.baseFields, ...topic.focusFields],
    publishedDate: worksheetPublishedDate,
  }))
);

